/* =====================================================
   LITM DATA · Themebooks aus Vol. 1
   System: Origin / Adventure / Greatness / Variable Might
   Quests: { title, description }
   Expanded entries: { text, expanded: true } oder { title, description, expanded: true }
===================================================== */

const THEMEBOOKS = {
  Circumstance: {
    type: 'Origin',
    titleTagSuggestions: [
      { text: 'gefallener Adel', hooks: ['adel','verlust'] },
      { text: 'flüchtiger Außenseiter', hooks: ['außenseiter','fahrend'] },
      { text: 'Schankhaus-Schläger', hooks: ['stadt','kampf'] },
      { text: 'einsamer Schänkengast', hooks: ['außenseiter','stadt'] },
      { text: 'verlorenes Erbe', hooks: ['adel','verlust'] },
      { text: 'Stimme des Volkes', hooks: ['macht','stadt'] },
      { text: 'verbannter Ritter', expanded: true, hooks: ['adel','außenseiter'] },
      { text: 'Tochter des Schmieds', expanded: true, hooks: ['handwerk'] },
      { text: 'fahrende Händlerin', expanded: true, hooks: ['fahrend','stadt'] },
      { text: 'Dorfaußenseiter mit Weitblick', expanded: true, hooks: ['außenseiter','natur'] },
      { text: 'Wanderprediger ohne Gemeinde', expanded: true, hooks: ['glaube','fahrend'] },
      { text: 'freie Leibeigene', expanded: true, hooks: ['außenseiter','verlust'] },
    ],
    powerTagPool: [
      { text: 'standesgemäße Kleidung', hooks: ['adel'] },
      { text: 'kennt jeden im Ort', hooks: ['stadt'] },
      { text: 'verlässliche Schaubühne', hooks: ['stadt'] },
      { text: 'sicheres Versteck', hooks: ['außenseiter','geheimnis'] },
      { text: 'Zunge wie ein Messer', hooks: ['stadt'] },
      { text: 'Standesvorrecht', hooks: ['adel','macht'] },
      { text: 'verborgene Gönner', hooks: ['adel','geheimnis'] },
      { text: 'durchschaut Masken', hooks: ['stadt','wissen'] },
      { text: 'kann sich verstecken', hooks: ['außenseiter','geheimnis'] },
      { text: 'ein Ort, wo ich frei bin', hooks: ['außenseiter','natur'] },
      { text: 'leise Beobachtung', hooks: ['geheimnis'] },
      { text: 'Hofmanieren', hooks: ['adel'] },
      { text: 'beschwichtigender Tonfall', hooks: ['stadt'] },
      { text: 'spricht für die Schwachen', hooks: ['glaube','macht'] },
      { text: 'Schloss aufbrechen', hooks: ['stadt','außenseiter'] },
      { text: 'spielt den Narren', hooks: ['stadt'] },
      { text: 'lebt vom Wenigen', hooks: ['außenseiter','verlust'] },
      { text: 'meine Leute halten zu mir', hooks: ['glaube','stadt'] },
      { text: 'kennt jeden Ausweg im Ort', expanded: true, hooks: ['stadt'] },
      { text: 'trägt ein falsches Siegel', expanded: true, hooks: ['adel','geheimnis'] },
      { text: 'weiß, wo die Leichen begraben sind', expanded: true, hooks: ['geheimnis','stadt'] },
      { text: 'hört die Gerüchte zuerst', expanded: true, hooks: ['stadt','geheimnis'] },
      { text: 'zieht keine Aufmerksamkeit auf sich', expanded: true, hooks: ['außenseiter','geheimnis'] },
      { text: 'hat einen alten Gönner in der Hauptstadt', expanded: true, hooks: ['adel','stadt'] },
      { text: 'spricht die Sprache der Straße', expanded: true, hooks: ['stadt','außenseiter'] },
      { text: 'findet immer eine Unterkunft für die Nacht', expanded: true, hooks: ['fahrend','stadt'] },
      { text: 'lächelt, wenn es brennt', expanded: true, hooks: ['stadt'] },
      { text: 'kennt den Preis jeder Stille', expanded: true, hooks: ['geheimnis'] },
      { text: 'überlebt in Verhältnissen, die andere brechen', expanded: true, hooks: ['verlust','außenseiter'] },
      { text: 'findet Verbündete, wo keine erwartet werden', expanded: true, hooks: ['stadt','glaube'] },
    ],
    weaknessTagPool: [
      { text: 'gehetzt von einer Macht', hooks: ['macht','verlust'] },
      { text: 'vom Standesdünkel verfolgt', hooks: ['adel'] },
      { text: 'gilt als Außenseiter', hooks: ['außenseiter'] },
      { text: 'verboten an manchen Orten', hooks: ['außenseiter','geheimnis'] },
      { text: 'Schulden, die mich einholen', hooks: ['verlust','stadt'] },
      { text: 'gebrochene Hände', hooks: ['verlust','handwerk'] },
      { text: 'hat einen Namen, der Unheil bringt', expanded: true, hooks: ['adel','verlust'] },
      { text: 'wird von alten Bekannten erkannt', expanded: true, hooks: ['geheimnis','verlust'] },
      { text: 'das Recht ist immer gegen sie', expanded: true, hooks: ['außenseiter','macht'] },
      { text: 'traut niemals ganz einer Person', expanded: true, hooks: ['außenseiter','verlust'] },
    ],
    questPool: [
      { title: 'Ich beweise meinen Wert trotz allem.', description: 'Andere haben mich abgeschrieben oder gar nicht erst gesehen. Jede Wahl, jede Tat ist eine stille Antwort: ich bin mehr, als sie meinten.', hooks: ['außenseiter','verlust'] },
      { title: 'Ich werde meinen alten Namen wiederherstellen.', description: 'Was einst Ehre und Ansehen hatte, liegt im Schmutz. Solange das so bleibt, finde ich keinen Frieden in dem, was ich bin.', hooks: ['adel','verlust'] },
      { title: 'Ich finde einen Ort, an dem ich frei sein kann.', description: 'Hier bin ich nur eine Last oder eine Beute. Irgendwo da draußen muss ein Platz sein, an dem ich einfach atmen darf.', hooks: ['außenseiter','fahrend'] },
      { title: 'Ich bleibe meiner Sippe treu, koste es, was es wolle.', description: 'Wer mich aufzog, wer mich kannte, als ich noch nichts war: für sie würde ich brennen. Das ist nicht verhandelbar.', hooks: ['glaube','stadt'] },
      { title: 'Ich zahle jede Schuld zurück, die ich gemacht habe.', description: 'Jede Gefälligkeit, jede geliehene Münze, jede Nacht, die mir jemand gab: ich führe Buch. Eines Tages ist das Konto ausgeglichen.', expanded: true, hooks: ['verlust','glaube'] },
      { title: 'Ich finde heraus, wer mich verraten hat.', description: 'Es war jemand aus meinem Kreis. Jemand, dem ich vertraute. Ich werde den Namen kennen, und dann werde ich entscheiden, was das bedeutet.', expanded: true, hooks: ['verlust','geheimnis'] },
      { title: 'Ich baue mir einen eigenen Platz in der Welt.', description: 'Kein geerbtes Gut, kein Almosen. Nur das, was ich mit meinen Händen und meinem Wort geschaffen habe.', expanded: true, hooks: ['handwerk','außenseiter'] },
      { title: 'Ich lasse nicht zu, dass sie mich vergessen.', description: 'Die Welt dreht sich weiter, als wäre ich nichts. Das werde ich ändern. Nicht durch Lärm, sondern durch Taten, die im Gedächtnis hängen.', expanded: true, hooks: ['macht','verlust'] },
    ]
  },

  Devotion: {
    type: 'Origin',
    titleTagSuggestions: [
      'Schwertschwur', 'Werdender Ritter', 'Verteidiger des Dorfes', 'Diener der Göttin', 'Pflegerin der Kranken', 'Liebe meines Lebens',
      { text: 'Hüterin des Tempels', expanded: true },
      { text: 'Schwester des Ordens', expanded: true },
      { text: 'Letzter Wächter', expanded: true },
      { text: 'Wächterin am Tor', expanded: true },
      { text: 'Verbündete der Ausgestoßenen', expanded: true },
      { text: 'Heilerin ohne Lohn', expanded: true },
    ],
    powerTagPool: [
      'Schwur ablegen', 'Mut sammeln', 'Schutzschild für die Schwachen', 'erinnert sich an einen Schwur', 'tröstet die Verzagten', 'kennt heilende Kräuter', 'einfache Heilkunst', 'spricht für die Stille', 'hält ein heiliges Symbol', 'Hände, die heilen', 'Ritualgesang', 'schützt mit dem eigenen Leib', 'sammelt Almosen für andere', 'kennt jedes Gebet', 'auf das Wort verlassen', 'schreitet ein, wo andere wegsehen',
      { text: 'betet, bevor sie kämpft', expanded: true },
      { text: 'trägt eine Wunde für andere', expanded: true },
      { text: 'gibt das Letzte, was sie hat', expanded: true },
      { text: 'spricht die Wahrheit, auch wenn sie wehtut', expanded: true },
      { text: 'hält aus, wenn andere aufgeben', expanded: true },
      { text: 'kennt die alten heiligen Orte', expanded: true },
      { text: 'ihre Stimme beruhigt Sterbende', expanded: true },
      { text: 'trägt ein Zeichen, das Böses abwehrt', expanded: true },
      { text: 'kennt den Namen jedes ihrer Schutzbefohlenen', expanded: true },
      { text: 'erkennt die Verzweiflung hinter einem Lächeln', expanded: true },
    ],
    weaknessTagPool: [
      'blind durch Hingabe', 'verpflichtet, nicht zu fliehen', 'jeder Schmerz der Gruppe ist meiner', 'die Pflicht verschlingt die Zeit', 'unbarmherzig gegen Verräter',
      { text: 'kann eine Bitte nicht ablehnen', expanded: true },
      { text: 'vergisst sich selbst über anderen', expanded: true },
      { text: 'leidet für jeden, dem sie nicht helfen konnte', expanded: true },
      { text: 'ihr Glaube wird ausgenutzt', expanded: true },
    ],
    questPool: [
      { title: 'Ich beschütze sie, bis ich sterbe.', description: 'Sie sind mir anvertraut, ob sie es wissen oder nicht. Solange ich atme, geschieht ihnen nichts.' },
      { title: 'Mein Gelübde halte ich, was auch geschieht.', description: 'Worte sind keine Münzen, die man ausgibt. Was ich versprochen habe, das tue ich, auch wenn die Welt sich gegen mich stellt.' },
      { title: 'Ich bringe das Heiligtum zurück, das wir verloren haben.', description: 'Ohne diesen Ort ist mein Volk gebrochen. Ich werde Wege gehen, die niemand sonst zu gehen wagt, um es zurückzuholen.' },
      { title: 'Ich bestehe die Pilgerfahrt.', description: 'Der Weg selbst ist die Prüfung. Erst wenn ich das Ziel erreiche, weiß ich, ob ich der war, für den ich mich gehalten habe.' },
      { title: 'Ich rette den Menschen, dem ich alles verdanke.', description: 'Ohne ihn, ohne sie wäre ich nicht, was ich bin. Jetzt ist es an mir, zurückzugeben.', expanded: true },
      { title: 'Ich halte das Licht aufrecht, solange ich kann.', description: 'Die Finsternis drückt von allen Seiten. Ich bin nicht stark genug, sie aufzuhalten. Aber ich weiche nicht zurück.', expanded: true },
      { title: 'Ich finde einen Nachfolger für das, was ich trage.', description: 'Das hier kann nicht mit mir enden. Die Pflicht ist größer als ich. Ich werde jemanden finden, der sie weiterträgt.', expanded: true },
      { title: 'Ich beweise, dass Treue mehr wert ist als Stärke.', description: 'Die Welt belohnt die Mächtigen. Ich werde zeigen, dass es einen anderen Weg gibt, mit Konsequenzen, die bleiben.', expanded: true },
    ]
  },

  Past: {
    type: 'Origin',
    titleTagSuggestions: [
      'Verflucht', 'Im Krieg geschmiedet', 'Letzter meines Volkes', 'mystischer Pilger', 'aus den Trümmern', 'der Heimkehrer',
      { text: 'Überlebende des Großen Feuers', expanded: true },
      { text: 'entflohener Gefangener', expanded: true },
      { text: 'Kind des verlorenen Krieges', expanded: true },
      { text: 'Einzige, die es weiß', expanded: true },
      { text: 'Getriebene ohne Heimat', expanded: true },
      { text: 'jemand, der alles hinter sich ließ', expanded: true },
    ],
    powerTagPool: [
      'altes Andenken', 'narbiges Schwertarm', 'Sprache der Verlorenen', 'Erinnerungen, die warnen', 'getragene Reisetracht', 'durchgemacht und überlebt', 'kennt das Schlachtfeld', 'spürt einen Fluch', 'hat die Ruinen gesehen', 'einst gelernte Liturgie', 'eiserner Wille', 'sieht durch Lügen', 'Erinnerungsstück eines Toten', 'eine Lektion aus Leid', 'kennt den Weg zurück', 'spricht eine vergessene Zunge',
      { text: 'erkennt eine Falle, bevor sie zuschnappt', expanded: true },
      { text: 'hat überlebt, was andere gebrochen hätte', expanded: true },
      { text: 'trägt die Narben mit Würde', expanded: true },
      { text: 'weiß, was es kostet, aufzugeben', expanded: true },
      { text: 'kennt die Namen der Toten', expanded: true },
      { text: 'schläft leicht und wacht sofort', expanded: true },
      { text: 'lernt aus jedem Fehler genau einmal', expanded: true },
      { text: 'sein Blick hat das Schlimmste gesehen', expanded: true },
      { text: 'trägt keine nutzlose Last mehr', expanded: true },
      { text: 'findet Orientierung, wo andere sich verlieren', expanded: true },
    ],
    weaknessTagPool: [
      'Albträume kehren wieder', 'verfolgt von alten Feinden', 'das Mal des Fluches', 'eine Schuld, die nie erlischt', 'Erinnerung schmerzt',
      { text: 'kann Vergangenheit nicht loslassen', expanded: true },
      { text: 'handelt manchmal, als wäre damals noch jetzt', expanded: true },
      { text: 'bestimmte Orte machen sie wehrlos', expanded: true },
      { text: 'vertraut niemandem, den sie nicht aus der alten Zeit kennt', expanded: true },
    ],
    questPool: [
      { title: 'Ich finde heraus, was wirklich geschah.', description: 'Die Geschichte, die man mir erzählt hat, hat Risse. Ich werde nicht eher ruhen, bis ich die Wahrheit selbst gesehen habe.' },
      { title: 'Ich befreie mich von dem, was mich bindet.', description: 'Etwas hängt an mir: ein Fluch, eine Schuld, ein Schatten. Solange er bleibt, gehört mein Leben mir nicht ganz.' },
      { title: 'Ich bringe das Vergangene zur Ruhe.', description: 'Die Geister meines früheren Lebens lassen mich nicht schlafen. Ich werde tun, was nötig ist, damit sie endlich schweigen.' },
      { title: 'Ich rette, was noch zu retten ist.', description: 'Vieles ist verloren, doch nicht alles. Solange irgendwo ein Funken glimmt, gebe ich nicht auf.' },
      { title: 'Ich suche den, der mich damals im Stich gelassen hat.', description: 'Sie haben sich abgewendet, als ich sie gebraucht hätte. Ich trage das noch, und ich muss entscheiden, was ich damit mache.', expanded: true },
      { title: 'Ich baue neu, was einst zerstört wurde.', description: 'Aus den Trümmern lässt sich etwas machen. Ich weiß das, weil ich selbst aus Trümmern bin.', expanded: true },
      { title: 'Ich vergebe dem, der mir Unrecht tat.', description: 'Nicht weil sie es verdienen. Sondern weil ich ohne diese Last weiter komme.', expanded: true },
      { title: 'Ich beende, was mein Volk nicht enden konnte.', description: 'Es blieb unfertig. Solange ich lebe, gibt es noch eine Chance, dass es abgeschlossen wird, wenn auch durch meine Hand.', expanded: true },
    ]
  },

  People: {
    type: 'Origin',
    titleTagSuggestions: [
      'Sylvenelf', 'Highlanderin', 'Battlerider', 'Hexenblut', 'Karawanenvolk', 'Bibervolk',
      { text: 'Fjordgeborene', expanded: true },
      { text: 'Tochter der Wanderer', expanded: true },
      { text: 'Küstenkind', expanded: true },
      { text: 'Sumpfbewohner', expanded: true },
      { text: 'Halbblut zwischen zwei Welten', expanded: true },
      { text: 'aus dem fernen Osten', expanded: true },
    ],
    powerTagPool: [
      'kennt die Sitten meines Volkes', 'altertümliches Lied', 'angeborener Sinn für Spuren', 'Werkzeug aus der Heimat', 'Bogen meines Volkes', 'wettergegerbte Haut', 'die Sprache der Ahnen', 'Tracht meines Volkes', 'Ruf der Verbündeten', 'unerwartete Stärke', 'angeborene Schnelligkeit', 'leiser Schritt', 'Schwert meines Volkes', 'Heimischer Boden gibt Kraft', 'sieht im Dunkeln', 'Affinität zu Tieren',
      { text: 'kennt die Zeichen des Wetters', expanded: true },
      { text: 'spürt fremdes Unrecht wie einen Stich', expanded: true },
      { text: 'Gesang, der die Seele bewegt', expanded: true },
      { text: 'trägt das Wissen der Alten', expanded: true },
      { text: 'kennt Pflanzen, die in keinem Buch stehen', expanded: true },
      { text: 'kann Feuer unter allen Bedingungen entfachen', expanded: true },
      { text: 'überlebt in Gebieten, die andere fliehen', expanded: true },
      { text: 'Tanz, der Bedeutung trägt', expanded: true },
      { text: 'Körpersprache, die kein Fremder liest', expanded: true },
      { text: 'kennt den Unterschied zwischen Gast und Eindringling', expanded: true },
    ],
    weaknessTagPool: [
      'gemieden in dieser Gegend', 'angeborene Schwäche', 'misstrauisch gegen Fremde', 'aus dem Element gerissen', 'auffälliges Merkmal',
      { text: 'die Sitten der Außenwelt sind fremd', expanded: true },
      { text: 'spricht die Sprache hier mit Akzent', expanded: true },
      { text: 'loyaler als vernünftig', expanded: true },
      { text: 'die eigene Kultur versteht bestimmte Dinge nicht', expanded: true },
    ],
    questPool: [
      { title: 'Ich erhebe mein Volk wieder zu Würde.', description: 'Wir sind mehr als die Geschichten, die andere über uns erzählen. Ich werde es ihnen zeigen, mit jedem Schritt, den ich gehe.' },
      { title: 'Ich erfülle eine Prophezeiung meiner Sippe.', description: 'Die Alten sahen voraus, was kommen würde, und sie sahen mich darin. Ich kann mich dem nicht entziehen, auch wenn ich es wollte.' },
      { title: 'Ich bewahre die Lieder meines Volkes vor dem Vergessen.', description: 'Wer keine Lieder mehr hat, hat kein Volk. Ich trage sie weiter, von Mund zu Mund, bis sie wieder Heimat finden.' },
      { title: 'Ich finde meinesgleichen.', description: 'Irgendwo dort draußen müssen sie sein, die wie ich sind. Mein Schritt geht in ihre Richtung, auch wenn ich noch nicht weiß, wohin.' },
      { title: 'Ich bringe Frieden zwischen mein Volk und ihre alten Feinde.', description: 'Der Krieg ist alt und keiner erinnert sich noch, warum er begann. Ich werde der sein, der sich erinnert und trotzdem die Hand ausstreckt.', expanded: true },
      { title: 'Ich finde das verlorene Herz meiner Kultur.', description: 'Etwas wurde uns genommen, ein Ort, ein Ritual, ein Name. Ich werde es zurückholen, damit wir wieder wissen, wer wir sind.', expanded: true },
      { title: 'Ich beweise, dass mein Volk mehr ist als sein Ruf.', description: 'Die anderen erzählen Geschichten über uns, alte und falsche. Mit jedem Atemzug schreibe ich eine andere.', expanded: true },
      { title: 'Ich überbrücke die Welten, in denen ich lebe.', description: 'Ich bin weder ganz von hier noch ganz von dort. Vielleicht ist das kein Fluch. Vielleicht ist es genau das, was gebraucht wird.', expanded: true },
    ]
  },

  Personality: {
    type: 'Origin',
    titleTagSuggestions: [
      'Herz aus Gold', 'das gelbe Lächeln', 'mürrisch wie Stein', 'übte Lügnerin', 'unstillbar neugierig', 'tröstet die Welt',
      { text: 'gefährlich gutgläubig', expanded: true },
      { text: 'das ruhige Auge im Sturm', expanded: true },
      { text: 'sagt, was sie denkt, immer', expanded: true },
      { text: 'lacht zuletzt', expanded: true },
      { text: 'hält Geheimnisse wie Atemluft', expanded: true },
      { text: 'zu neugierig für ihr eigenes Wohl', expanded: true },
    ],
    powerTagPool: [
      'durchschaut eine Lüge', 'Lacher in dunkler Stunde', 'frohe Geschichte', 'Sturheit als Tugend', 'einnehmendes Lächeln', 'kennt die richtige Frage', 'gibt anderen Hoffnung', 'kalter Blick', 'einschüchterndes Auftreten', 'einfühlsame Stille', 'spielt den Narren', 'sucht nach der Wahrheit', 'plaudert sich aus jeder Lage', 'gibt einen Rat, der hilft', 'macht Mut zum Aufstehen', 'keine Gerüchte entgehen mir',
      { text: 'bringt jeden zum Reden', expanded: true },
      { text: 'erkennt, wenn jemand Hilfe braucht, bevor er es sagt', expanded: true },
      { text: 'behält die Ruhe, wenn andere ausrasten', expanded: true },
      { text: 'verbreitet Zuversicht wie eine Krankheit', expanded: true },
      { text: 'findet in jeder Lage etwas Absurdes', expanded: true },
      { text: 'liest Räume sofort', expanded: true },
      { text: 'weicht einem Konflikt nie aus, wenn er wichtig ist', expanded: true },
      { text: 'trägt Groll nicht länger als eine Nacht', expanded: true },
      { text: 'stellt die richtige Frage zur richtigen Zeit', expanded: true },
      { text: 'gibt nie auf, ohne alles versucht zu haben', expanded: true },
    ],
    weaknessTagPool: [
      'leicht zu provozieren', 'sentimental im falschen Moment', 'ausnutzbar', 'spricht zu viel', 'erwartet Anerkennung',
      { text: 'zu ehrlich für ihr eigenes Wohl', expanded: true },
      { text: 'nimmt sich alles zu Herzen', expanded: true },
      { text: 'kann schlechte Stimmung nicht ignorieren', expanded: true },
      { text: 'verliert sich in Details, die sie interessieren', expanded: true },
    ],
    questPool: [
      { title: 'Ich bleibe mir treu, koste es, was es wolle.', description: 'Lieber zerbreche ich, als dass ich mich biege. Wer ich bin, ist das Einzige, das mir wirklich gehört.' },
      { title: 'Ich helfe denen, die sonst niemand sieht.', description: 'Die Welt rauscht an den Schwachen vorbei. Ich tue es nicht, denn ich war einmal einer von ihnen.' },
      { title: 'Ich verstehe endlich, wer ich wirklich bin.', description: 'All meine Masken sind alt geworden. Ich werde sie eine nach der anderen abnehmen und schauen, was darunter ist.' },
      { title: 'Ich bringe Licht in dunkle Räume.', description: 'Wo Verzweiflung herrscht, brauche ich keine Schwerter. Ein Lachen, ein Lied, eine Hand reichen oft.' },
      { title: 'Ich finde die, die mir wirklich vertrauen.', description: 'Es gibt Menschen, die mich kennen, wie ich wirklich bin. Die will ich finden, und für sie will ich da sein.', expanded: true },
      { title: 'Ich lerne, auch für mich selbst da zu sein.', description: 'Für andere einzustehen fällt mir leicht. Das hier ist die schwierigere Übung: mir selbst nicht im Weg zu stehen.', expanded: true },
      { title: 'Ich ändere etwas in dieser Welt durch Worte, nicht durch Schwerter.', description: 'Ideen sind haltbarer als Stahl. Ich werde etwas sagen oder schreiben, das noch hallt, wenn ich nicht mehr bin.', expanded: true },
      { title: 'Ich gebe das Gute, das mir getan wurde, weiter.', description: 'Jemand hat mir geholfen, als ich es nicht verdiente. Das geht von mir aus weiter. So weit ich reiche.', expanded: true },
    ]
  },

  'Skill or Trade': {
    type: 'Origin',
    titleTagSuggestions: [
      'Hinterland-Spurenleser', 'Schmied der Berge', 'taschendiebischer Wandersmann', 'Heilkundige', 'Steuermann', 'Bogenbauer',
      { text: 'Gerber am Fluss', expanded: true },
      { text: 'Brauerin der alten Rezepte', expanded: true },
      { text: 'Kräutersammlerin', expanded: true },
      { text: 'Bote der schnellen Füße', expanded: true },
      { text: 'Tischler der feinen Art', expanded: true },
      { text: 'Seiltänzerin auf Jahrmärkten', expanded: true },
    ],
    powerTagPool: [
      'meisterhaft an der Esse', 'Werkzeug meines Handwerks', 'kennt jede Spur im Wald', 'gut sortierte Vorratskammer', 'flinke Finger', 'liest die Karte', 'kennt jeden Knoten', 'Pfeil und Bogen geübt', 'eingespielte Schrittfolge', 'Stahl bis zur Klinge', 'leise Schritte', 'fester Griff', 'umgeht jede Wache', 'gut gemachte Werkzeuge', 'fachkundiger Blick', 'verlässliche Routine',
      { text: 'repariert, was andere wegwerfen', expanded: true },
      { text: 'kennt den Preis jedes Rohstoffs', expanded: true },
      { text: 'sieht sofort, ob etwas gut gemacht ist', expanded: true },
      { text: 'schätzt Entfernungen und Gewichte genau', expanded: true },
      { text: 'baut in der Dunkelheit, was andere am Tag nicht schaffen', expanded: true },
      { text: 'lernt ein neues Werkzeug in Stunden', expanded: true },
      { text: 'löst Probleme mit dem, was gerade da ist', expanded: true },
      { text: 'arbeitet schnell ohne Fehler', expanded: true },
      { text: 'kennt jedes Material an Geruch und Gefühl', expanded: true },
      { text: 'kennt die Schwachstelle jeder Konstruktion', expanded: true },
    ],
    weaknessTagPool: [
      'überfordert ohne Werkzeug', 'wirkt einseitig', 'misstrauisch beobachtet', 'oft erschöpft vom Üben', 'kennt nur eine Welt',
      { text: 'Berufsehre macht kompromisslos', expanded: true },
      { text: 'sieht Pfusch nicht ohne Reaktion', expanded: true },
      { text: 'schlechte Verhandlungskünste', expanded: true },
      { text: 'verliert sich in der Arbeit', expanded: true },
    ],
    questPool: [
      { title: 'Ich werde der Beste in meinem Fach.', description: 'Andere sollen meinen Namen nennen, wenn sie an Meisterschaft denken. Bis dahin lasse ich keinen Stein der Übung unberührt.' },
      { title: 'Ich bewahre mein Handwerk vor dem Vergessen.', description: 'Das, was ich kann, droht zu verschwinden. Solange ich lehre und übe, bleibt ein Funken davon lebendig.' },
      { title: 'Ich finde Anwendung für meine Kunst, die wirklich zählt.', description: 'Ich kann mehr, als nur Geld dafür zu nehmen. Irgendwo wartet die Aufgabe, die meinem Können einen Sinn gibt.' },
      { title: 'Ich gebe mein Wissen weiter.', description: 'Was ich gelernt habe, soll nicht mit mir sterben. Ich finde die, die es brauchen, und übergebe es ihnen mit ruhigen Händen.' },
      { title: 'Ich stelle das schwierigste Stück her, das je gemacht wurde.', description: 'Nicht für Lob oder Geld. Weil ich wissen muss, ob ich kann, was kein anderer kann.', expanded: true },
      { title: 'Ich räche die Ehre meines Gewerbes.', description: 'Jemand hat meinen Stand beschmutzt oder meinen Lehrherrn zu Fall gebracht. Ich werde dafür sorgen, dass das nicht unbeantwortet bleibt.', expanded: true },
      { title: 'Ich nutze mein Handwerk, um jemandem das Leben zu retten.', description: 'Es geht nicht um Kunst oder Ruhm. Es geht darum, dass meine Hände heute das Richtige tun.', expanded: true },
      { title: 'Ich baue etwas, das die Prüfung der Zeit besteht.', description: 'Alles verwittert, alles bricht. Ich will einmal etwas erschaffen, das noch steht, wenn ich längst weg bin.', expanded: true },
    ]
  },

  Trait: {
    type: 'Origin',
    titleTagSuggestions: [
      'stark wie ein Ochse', 'akrobatische Beweglichkeit', 'unheimlich schön', 'prophetische Visionen', 'Kraft des Wassers', 'unerschütterlich',
      { text: 'unsichtbar in jedem Raum', expanded: true },
      { text: 'hört Herzschläge durch Mauern', expanded: true },
      { text: 'spürt Lügen körperlich', expanded: true },
      { text: 'Augen wie ein Falke', expanded: true },
      { text: 'nie vollständig verwundbar', expanded: true },
      { text: 'Stimme, die Mauern bewegt', expanded: true },
    ],
    powerTagPool: [
      'leichter Schritt', 'unbändige Kraft', 'unverwundbar wirkende Schönheit', 'sieht, was kommen wird', 'spricht im Schlaf', 'springt höher als andere', 'taucht tief und lange', 'fühlt magische Spuren', 'unermüdlich', 'klettert wie eine Katze', 'ungewöhnlich präzise', 'lacht, wo andere schreien', 'übermenschliche Sinne', 'erinnert sich an alles', 'sehr geschickt', 'sieht im Halbdunkel',
      { text: 'läuft ohne Ermüdung stundenlang', expanded: true },
      { text: 'instinktive Reaktion auf Gefahr', expanded: true },
      { text: 'spürt Stimmungen in Räumen', expanded: true },
      { text: 'hält Temperaturen aus, die andere umbringen', expanded: true },
      { text: 'regeneriert schneller als normal', expanded: true },
      { text: 'körperliches Gedächtnis für Bewegungen', expanded: true },
      { text: 'übertrifft Erwartungen ohne zu ahnen, warum', expanded: true },
      { text: 'hört Falschherzigkeit in der Stimme', expanded: true },
      { text: 'zieht Aufmerksamkeit an wie Licht Motten', expanded: true },
      { text: 'kann sich auf einen Punkt konzentrieren, ohne abzuschweifen', expanded: true },
    ],
    weaknessTagPool: [
      'auffällig für Feinde', 'wird beneidet', 'erschöpft sich rasch', 'wirkt befremdlich', 'unbeholfen ohne Gabe',
      { text: 'die Gabe schlägt manchmal ungefragt zu', expanded: true },
      { text: 'das Ungewöhnliche zieht Neugier an, nicht immer gutartige', expanded: true },
      { text: 'die Gabe hat Grenzen, die sie erst beim Versagen kennt', expanded: true },
      { text: 'anderen gegenüber ungeduldig wegen der Gabe', expanded: true },
    ],
    questPool: [
      { title: 'Ich finde heraus, woher meine Gabe stammt.', description: 'Das, was ich kann, kann nicht aus dem Nichts gekommen sein. Ich werde der Spur folgen, bis ich an ihren Anfang gelange.' },
      { title: 'Ich nutze meine Gabe für etwas Größeres.', description: 'Was ich bin, ist mir nicht für mich allein gegeben worden. Ich finde heraus, wofür sie wirklich bestimmt ist.' },
      { title: 'Ich versuche, normal zu sein.', description: 'Mein ganzes Leben war ich anders. Vielleicht ist es Zeit, einmal zu lernen, wie es sich anfühlt, einer von vielen zu sein.' },
      { title: 'Ich überwinde die Grenzen meiner Gabe.', description: 'Andere glauben, sie wissen, was ich kann. Aber sie haben das Ende noch nicht gesehen, und ich auch nicht.' },
      { title: 'Ich lerne, meine Gabe zu beherrschen, bevor sie mich beherrscht.', description: 'Es gibt Momente, in denen sie mich übermannt. Das wird aufhören. Ich werde es aufhören lassen.', expanded: true },
      { title: 'Ich finde jemanden, der meine Gabe teilt.', description: 'Noch niemand hat mir gesagt, dass er mich versteht, weil er dasselbe kennt. Das wäre anders als alles bisher.', expanded: true },
      { title: 'Ich trage die Last meiner Gabe, ohne daran zugrunde zu gehen.', description: 'Sie kostet mich etwas, das sich nicht benennen lässt. Ich werde einen Weg finden, damit zu leben, der mich nicht zerstört.', expanded: true },
      { title: 'Ich nutze das Ungewöhnliche in mir, um eine ungewöhnliche Aufgabe zu erfüllen.', description: 'Für gewöhnliche Probleme gibt es gewöhnliche Lösungen. Für das hier braucht es genau das, was ich bin.', expanded: true },
    ]
  },

  Duty: {
    type: 'Adventure',
    titleTagSuggestions: [
      'Licht gegen die Finsternis', 'auf Vertrag', 'Schwur dem Lehnsherrn', 'Hüterin des Landes', 'Rachezwang', 'Bote des Königs',
      { text: 'Schwertarm des Ordens', expanded: true },
      { text: 'Wächterin der Grenzmark', expanded: true },
      { text: 'letzter Zeuge eines Vertrags', expanded: true },
      { text: 'Schuldenbegleicherin', expanded: true },
      { text: 'bezahlter Verteidiger', expanded: true },
      { text: 'Vollstreckerin des alten Gesetzes', expanded: true },
    ],
    powerTagPool: [
      'leuchtende Rüstung', 'kennt die Verbündeten der Sache', 'kraftvoller Schwur', 'Banner meines Lehnsherrn', 'Recht auf freien Durchgang', 'Recht auf Kost und Quartier', 'mein Eid macht mich stark', 'kennt das Reich von Norden bis Süden', 'gefürchteter Gegner des Bösen', 'Vertrag in der Hand', 'Anweisungen ausführen', 'kommandiert Soldaten', 'kennt Strategien des Kampfes', 'unbeirrbar im Zweck',
      { text: 'kennt die Grenzen ihres Auftrags genau', expanded: true },
      { text: 'handelt auch ohne Anweisung richtig', expanded: true },
      { text: 'trägt die Autorität ihres Hauses', expanded: true },
      { text: 'kann Legitimität einfordern', expanded: true },
      { text: 'kennt jede Losung jeder Wache', expanded: true },
      { text: 'setzt Befehle durch, ohne Feinde zu machen', expanded: true },
      { text: 'kennt die Regeln und ihre Ausnahmen', expanded: true },
      { text: 'hält eine Stellung, wenn alle anderen fliehen', expanded: true },
      { text: 'wird nicht gekauft, auch nicht für viel Gold', expanded: true },
      { text: 'macht klare Abmachungen und hält sich daran', expanded: true },
    ],
    weaknessTagPool: [
      'rivalisiert um die Aufgabe', 'verhasst bei Feinden des Auftrags', 'fühlt Schuld bei Versagen', 'an Befehle gebunden',
      { text: 'kann Ordres nicht widersprechen, auch wenn falsch', expanded: true },
      { text: 'der Auftrag steht über allem, auch der Vernunft', expanded: true },
      { text: 'trägt Schuld für jeden, der unter dem Auftrag leidet', expanded: true },
      { text: 'beendet nie einen Auftrag, egal wie lange er dauert', expanded: true },
    ],
    questPool: [
      { title: 'Ich erfülle meinen Schwur, koste es, was es wolle.', description: 'Was ich versprochen habe, ist mehr als ein Wort. Es ist die Achse, um die mein Leben sich dreht.' },
      { title: 'Ich bringe die Auftraggeber zu Fall, wenn sie das Versprechen brechen.', description: 'Wer mich für etwas einspannt, das verlogen ist, wird meinen Zorn kennenlernen. Auch wenn er der Mächtige ist.' },
      { title: 'Ich räche das Unrecht, das mir geschah.', description: 'Ich habe es nicht vergessen, und ich werde es auch nicht. Erst wenn die Schuld beglichen ist, finde ich Schlaf.' },
      { title: 'Ich beschütze das Land, dem ich diene.', description: 'Diese Erde, diese Menschen — das ist mein Auftrag und mein Anker. Wer ihnen schadet, schadet mir.' },
      { title: 'Ich führe den Auftrag zu Ende, den mein Vorgänger nicht beenden konnte.', description: 'Sie sind gefallen, als noch alles offen war. Ich nehme auf, was sie hinterließen, und ich bringe es zu einem Ende.', expanded: true },
      { title: 'Ich finde heraus, ob der Auftrag, dem ich gedient habe, gerecht war.', description: 'Lange habe ich nicht gefragt. Jetzt trage ich die Antwort wie einen Stein. Ich werde wissen, für wen ich geblutet habe.', expanded: true },
      { title: 'Ich beende die Pflicht in Würde.', description: 'Irgendwann ist ein Dienst getan. Ich will den Abschluss nicht verschleppen oder verdrängen, sondern mit Kopf und Herzen vollziehen.', expanded: true },
      { title: 'Ich baue eine Ordnung, die meine Arbeit überflüssig macht.', description: 'Wenn alles gut geht, braucht man am Ende keine Wächter mehr. Das ist der eigentliche Sieg.', expanded: true },
    ]
  },

  Influence: {
    type: 'Adventure',
    titleTagSuggestions: [
      'Dockmeisterin', 'graue Eminenz', 'Stadtrat', 'Gildenführer', 'Anführerin der Schmuggler', 'Diplomatin',
      { text: 'Händlerin mit dem Netz', expanded: true },
      { text: 'Beraterin im Verborgenen', expanded: true },
      { text: 'Mäzenin der Armen', expanded: true },
      { text: 'Schiedsrichterin der Straßen', expanded: true },
      { text: 'Königsmacherin', expanded: true },
      { text: 'Stimme des Rates', expanded: true },
    ],
    powerTagPool: [
      'Spitzel an jeder Ecke', 'kennt die wahren Mächte der Stadt', 'spricht mit Befehlsgewalt', 'Gefälligkeiten einfordern', 'Gold öffnet Türen', 'eine Karte mit allen Namen', 'Boten in jede Richtung', 'Briefe öffnen Tore', 'kennt das Geheimnis aller', 'Gildensiegel', 'Recht auf Audienz', 'Beobachter überall', 'Schatzkammer im Hintergrund', 'Vertrauen der Mächtigen',
      { text: 'kann Verbündete mobilisieren', expanded: true },
      { text: 'zieht Fäden, ohne selbst sichtbar zu sein', expanded: true },
      { text: 'stellt einen Ruf zur Verfügung oder nimmt ihn weg', expanded: true },
      { text: 'kennt die Schulden aller Beteiligten', expanded: true },
      { text: 'hat Zugang zu Orten, die andere nicht kennen', expanded: true },
      { text: 'beeinflusst Entscheidungen durch Fragen, nicht Befehle', expanded: true },
      { text: 'setzt Gerüchte wie Werkzeuge ein', expanded: true },
      { text: 'hält Informationen, bis sie den größten Effekt haben', expanded: true },
      { text: 'eine Geste von ihr genügt', expanded: true },
      { text: 'weiß, was verschwiegen werden will', expanded: true },
    ],
    weaknessTagPool: [
      'Konkurrenz um die Position', 'erpressbar durch Geheimnisse', 'der Hof ist ein Schlangennest', 'unsichtbare Feinde',
      { text: 'zu viele Verpflichtungen, zu wenig Loyalität', expanded: true },
      { text: 'jedes Bündnis hat seinen Preis', expanded: true },
      { text: 'wer Macht hat, ist ein Ziel', expanded: true },
      { text: 'Intrigen, die sie einst initiierte, kommen zurück', expanded: true },
    ],
    questPool: [
      { title: 'Ich verteidige meine Position bis zum Ende.', description: 'Was ich aufgebaut habe, gebe ich nicht her. Wer es mir nehmen will, soll wissen, wie viel es mich gekostet hat.' },
      { title: 'Ich nutze meinen Einfluss, um die Welt zu wenden.', description: 'Macht ohne Sinn ist Selbstzweck. Ich werde sie nutzen, solange sie mir gehört, und etwas hinterlassen, das bleibt.' },
      { title: 'Ich entlarve die wahren Strippenzieher.', description: 'Hinter allem, was offen geschieht, bewegen sich verborgene Hände. Ich werde sie finden und ans Licht zerren.' },
      { title: 'Ich werde der Mächtigste in dieser Stadt.', description: 'Hier bin ich noch ein Stein unter vielen. Aber ich kenne meinen Weg an die Spitze, und niemand wird mich aufhalten.' },
      { title: 'Ich nutze meinen Einfluss, um das Unrecht, das ich getan habe, wiedergutzumachen.', description: 'Es war Macht, die mich korrumpierte. Jetzt ist es Macht, mit der ich den Schaden begrenze. Wenn es noch geht.', expanded: true },
      { title: 'Ich baue ein Netzwerk, das nach mir weiterlebt.', description: 'Was ich aufgebaut habe, soll nicht mit mir enden. Ich wähle Nachfolger und stelle Strukturen auf, damit der Einfluss bleibt.', expanded: true },
      { title: 'Ich beende die Abhängigkeit, in die ich mich manövriert habe.', description: 'Alle Fäden enden irgendwo. Irgendwo enden sie auch bei mir. Ich will nicht mehr der letzte in dieser Kette sein.', expanded: true },
      { title: 'Ich finde heraus, wer mich wirklich kontrolliert.', description: 'Ich dachte, ich zöge die Fäden. Inzwischen zweifle ich daran. Es ist Zeit, die Wahrheit zu kennen.', expanded: true },
    ]
  },

  Knowledge: {
    type: 'Adventure',
    titleTagSuggestions: [
      'Sterndeuter', 'Bewohner des Verborgenen', 'kennt jedes Land', 'Bibliothekar des Verbotenen', 'Studium der alten Reiche', 'Sprachgelehrter',
      { text: 'Kartografin vergessener Wege', expanded: true },
      { text: 'Entschlüsslerin alter Schriften', expanded: true },
      { text: 'Schülerin verbotenen Wissens', expanded: true },
      { text: 'Hüterin der verborgenen Archive', expanded: true },
      { text: 'Kennerin der Naturgesetze', expanded: true },
      { text: 'Forscherin der alten Kulte', expanded: true },
    ],
    powerTagPool: [
      'liest in den Sternen', 'kennt die alten Sprachen', 'erkennt jedes Symbol', 'sieht die Zeichen', 'kennt verbotene Riten', 'erinnert sich an jedes Buch', 'analysiert eine Substanz', 'übersetzt jede Schrift', 'kennt Bestienkunde', 'führt geheime Forschung', 'ein Lexikon an Lore', 'kennt den Weg zur Wahrheit', 'spricht die Sprache der Toten', 'kennt jedes Provinzwappen',
      { text: 'findet Zusammenhänge, die niemand sonst sieht', expanded: true },
      { text: 'kennt den historischen Kontext jeder Lage', expanded: true },
      { text: 'weiß, welche Quellen man nicht glauben darf', expanded: true },
      { text: 'kann aus Fragmenten ein Ganzes rekonstruieren', expanded: true },
      { text: 'kennt die Schwäche jedes bekannten Wesens', expanded: true },
      { text: 'fragt die richtigen Fragen', expanded: true },
      { text: 'vergisst nie, was sie einmal gelesen hat', expanded: true },
      { text: 'erkennt Manipulation in historischen Berichten', expanded: true },
      { text: 'kennt Routen, die kein Reisebuch verzeichnet', expanded: true },
      { text: 'nutzt Wissen als Hebel, selten als Waffe', expanded: true },
    ],
    weaknessTagPool: [
      'gefährliches Wissen anziehend für Feinde', 'verloren in der Welt der Bücher', 'körperlich nicht stark', 'verfolgt von neugierigen Mächten',
      { text: 'die Wahrheit ist ihr wichtiger als das Wohl anderer', expanded: true },
      { text: 'unterschätzt die Gefahr von Wissen in der Praxis', expanded: true },
      { text: 'wird für ihr Wissen benutzt', expanded: true },
      { text: 'das Wissen kostet: Schlaf, Gesellschaft, Gesundheit', expanded: true },
    ],
    questPool: [
      { title: 'Ich enthülle die letzte Wahrheit, koste es, was es wolle.', description: 'Es gibt eine Antwort, hinter all den Schleiern und Lügen. Ich werde sie sehen, auch wenn sie mich zerbricht.' },
      { title: 'Ich bewahre dieses Wissen vor dem Falschen.', description: 'In den falschen Händen wäre dieses Wissen Gift. Ich trage es, damit es niemand anders muss.' },
      { title: 'Ich finde die Quelle der alten Lieder.', description: 'Sie sind nicht aus dem Nichts entstanden. Irgendwo muss der Brunnen sein, aus dem sie geflossen sind.' },
      { title: 'Ich verstehe, was niemand sonst versteht.', description: 'Was die anderen für ein Rätsel halten, kann ich auflösen. Wenn ich nur lange genug schaue und ehrlich genug frage.' },
      { title: 'Ich gebe das Wissen weiter, das gebraucht wird.', description: 'Was nützt es in meinem Kopf? Ich werde die richtigen Hände finden, die es tragen können.', expanded: true },
      { title: 'Ich beweise, dass das, was als Mythos gilt, wahr ist.', description: 'Alle lachen. Die Quellen sagen etwas anderes. Ich werde es beweisen, mit Fakten, nicht mit Glauben.', expanded: true },
      { title: 'Ich zerstöre das Wissen, das zu gefährlich ist.', description: 'Es gibt Dinge, die besser vergessen wären. Ich habe es zu lange mit mir getragen. Es endet hier.', expanded: true },
      { title: 'Ich finde einen anderen, der die Last des Wissens teilt.', description: 'Allein trägt man das nicht ewig. Ich suche jemanden, der versteht, was ich trage, und es gemeinsam mit mir hält.', expanded: true },
    ]
  },

  'Prodigious Ability': {
    type: 'Adventure',
    titleTagSuggestions: [
      'fesselnder Geschichtenerzähler', 'meisterhafter Koch', 'gefürchteter Klingenmeister', 'wundersamer Heiler', 'unbestechlicher Bogenschütze', 'Meister des Spiels',
      { text: 'Tänzerin ohne Gleichen', expanded: true },
      { text: 'Diebin des Unmöglichen', expanded: true },
      { text: 'Bardin der Legenden', expanded: true },
      { text: 'Reiterin, die kein Tier verliert', expanded: true },
      { text: 'Rednerin, die Massen bewegt', expanded: true },
      { text: 'Spielerin, die keine Partie verliert', expanded: true },
    ],
    powerTagPool: [
      'Schwertkunst, die staunen macht', 'eigene Signaturtechnik', 'verzaubert mit Worten', 'erfindet im Augenblick', 'staunenswerter Sprung', 'einmalige Heiltechnik', 'erkennt den schwachen Punkt', 'erkennt jeden Zauber', 'wundersames Werk', 'unfehlbarer Pfeil', 'unbestreitbare Eleganz', 'erstaunliche Geschwindigkeit', 'gilt als der Beste', 'reißt jede Menge mit',
      { text: 'übertrifft sich selbst, wenn es zählt', expanded: true },
      { text: 'die Technik ist unlesbar für andere', expanded: true },
      { text: 'kein Druck macht sie schlechter', expanded: true },
      { text: 'lehrt andere in Augenblicken, was Jahre braucht', expanded: true },
      { text: 'improvisiert Lösungen, die kein Lehrplan kennt', expanded: true },
      { text: 'stimmt die Vorführung auf das Publikum ab', expanded: true },
      { text: 'wiederholt kein Versagen zweimal', expanded: true },
      { text: 'sieht in wenigen Herzschlägen, was zu tun ist', expanded: true },
      { text: 'bringt andere dazu, besser zu sein', expanded: true },
      { text: 'erreicht das Ziel auf einem Weg, den niemand ahnt', expanded: true },
    ],
    weaknessTagPool: [
      'arrogant gegenüber Schwächeren', 'wird ständig herausgefordert', 'erschöpft im Alltag', 'misstrauisch beobachtet',
      { text: 'kann nicht verlieren, ohne es persönlich zu nehmen', expanded: true },
      { text: 'die Gabe macht einsam', expanded: true },
      { text: 'wird für Unmögliches eingespannt', expanded: true },
      { text: 'vergisst, dass andere ihr Tempo nicht mitgehen können', expanded: true },
    ],
    questPool: [
      { title: 'Ich werde unangefochten der Beste.', description: 'Es gibt nur einen Platz an der Spitze. Ich werde den, der dort steht, ablösen, und den, der nach mir kommt, nicht zulassen.' },
      { title: 'Ich gebe meine Kunst weiter, bevor ich sterbe.', description: 'Was in mir ist, soll nicht mit mir vergehen. Ich finde den, der bereit ist, es zu nehmen.' },
      { title: 'Ich vollbringe das Meisterwerk meines Lebens.', description: 'Ein Werk, das alles enthält, was ich bin. Erst dann darf ich Ruhe geben, nicht eher.' },
      { title: 'Ich nutze meine Gabe für etwas Würdiges.', description: 'Mein Können ist mehr als Schauspiel. Es muss seinen Platz finden, dort wo es wirklich zählt.' },
      { title: 'Ich beweise meine Fähigkeit in der schwersten Prüfung, die es gibt.', description: 'Kein Wettbewerb, keine Zurschaustellung. Die Aufgabe, bei der es darauf ankommt, ob sie gelingt oder versagt.', expanded: true },
      { title: 'Ich lerne, die Grenzen meiner Gabe anzuerkennen.', description: 'Ich kann fast alles, aber nicht alles. Das zu wissen und trotzdem nicht zu brechen, ist die eigentliche Meisterschaft.', expanded: true },
      { title: 'Ich finde denjenigen, der mir ebenbürtig ist.', description: 'Noch nie bin ich jemandem begegnet, der mich fordert. Ich werde denjenigen finden, und dann werden wir sehen, wer wir wirklich sind.', expanded: true },
      { title: 'Ich nutze mein Talent, nicht für Ruhm, sondern um etwas zu retten.', description: 'Es geht nicht um Beifall. Es geht darum, dass heute Nacht alles davon abhängt, dass ich das Richtige tue.', expanded: true },
    ]
  },

  Relic: {
    type: 'Adventure',
    titleTagSuggestions: [
      'die Riesenfaust', 'Beutel mit Zauberstaub', 'Kessel der Beschwörung', 'verfluchte Klinge', 'Stab der alten Zeiten', 'Krone der Vergessenen',
      { text: 'Spiegel, der Wahrheit zeigt', expanded: true },
      { text: 'Buch, das sich selbst schreibt', expanded: true },
      { text: 'Stein der alten Festung', expanded: true },
      { text: 'Kette des letzten Königs', expanded: true },
      { text: 'Schlüssel ohne Schloss', expanded: true },
      { text: 'Kapsel mit vergessenen Stimmen', expanded: true },
    ],
    powerTagPool: [
      'donnernder Faustschlag', 'beschwört nützliche Dinge', 'lauscht den Geistern', 'der Stein flüstert mir zu', 'die Klinge schneidet alles', 'Kraft aus dem Artefakt', 'wärmt die Seele', 'leuchtet im Dunkeln', 'leitet zum Ziel', 'verbirgt mich vor Bösem', 'enthüllt verborgene Wahrheiten', 'bindet feindliche Magie', 'der Helm zeigt Visionen', 'die Münze kommt zurück',
      { text: 'reagiert auf Gefahr, bevor ich es tue', expanded: true },
      { text: 'verstärkt das, was ich ohnehin kann', expanded: true },
      { text: 'öffnet Türen, die sonst verschlossen bleiben', expanded: true },
      { text: 'zeigt mir die Schwäche des Gegenübers', expanded: true },
      { text: 'kühlt Fieber und Fluch gleichermaßen', expanded: true },
      { text: 'spricht zu mir in Träumen', expanded: true },
      { text: 'gibt mir Kraft, wenn ich nichts mehr habe', expanded: true },
      { text: 'lockt die Richtigen an, hält die Falschen fern', expanded: true },
      { text: 'hat eine Geschichte, die sich mir erst langsam erschließt', expanded: true },
      { text: 'schützt mich auf eine Weise, die ich nicht erklären kann', expanded: true },
    ],
    weaknessTagPool: [
      'der Gegenstand hat einen eigenen Willen', 'Diebe begehren ihn', 'Magie hat ihren Preis', 'kann verloren gehen',
      { text: 'das Artefakt verändert mich subtil', expanded: true },
      { text: 'andere erkennen es und wollen es', expanded: true },
      { text: 'die Macht kommt mit Forderungen', expanded: true },
      { text: 'es ist nicht klar, ob ich es trage oder es mich', expanded: true },
    ],
    questPool: [
      { title: 'Ich entschlüssele das Geheimnis dieses Artefakts.', description: 'Es spricht zu mir in einer Sprache, die ich noch nicht ganz verstehe. Aber ich werde sie lernen, Wort für Wort.' },
      { title: 'Ich erfülle, was die alte Magie von mir verlangt.', description: 'Das Artefakt fordert etwas, und ich kann mich dem nicht entziehen. Ich höre, ich gehe, ich tue.' },
      { title: 'Ich bringe das Artefakt an seinen Ursprung zurück.', description: 'Es gehört nicht hierher. Mein Weg ist es, es nach Hause zu tragen, koste es, was es wolle.' },
      { title: 'Ich befreie mich von seinem Bann.', description: 'Es hat mich gewählt, doch ich habe nie zugestimmt. Eines Tages werde ich es ablegen können, ohne zu sterben.' },
      { title: 'Ich finde heraus, wer das Artefakt zuletzt besaß, und warum es ihn zerstörte.', description: 'Die Spur führt durch Jahrzehnte. Jede Person, die es hielt, endete anders als geplant. Ich will wissen, warum.', expanded: true },
      { title: 'Ich nutze das Artefakt für den einen Zweck, für den es erschaffen wurde.', description: 'Es hat einen Sinn. Nicht mehrere, nur einen. Ich habe lange gewartet, bis ich den Moment erkenne.', expanded: true },
      { title: 'Ich schütze das Artefakt vor denen, die es missbrauchen würden.', description: 'Es wäre eine Waffe in den falschen Händen. Ich bin seine Hüterin, ob ich das wollte oder nicht.', expanded: true },
      { title: 'Ich finde das zweite Stück des Artefakts.', description: 'Es ist unvollständig, und das fühlt man. Irgendwo ist das, was fehlt. Ich werde es nicht ruhen lassen, bis ich es halte.', expanded: true },
    ]
  },

  'Uncanny Being': {
    type: 'Adventure',
    titleTagSuggestions: [
      'körperloser Geist', 'Höllenkind', 'Kleiner Hob', 'Wechselgestalt', 'Mondgeborene', 'Schattenwandler',
      { text: 'halbwaches Traumkind', expanded: true },
      { text: 'Aschenwanderin', expanded: true },
      { text: 'Wassergeborene', expanded: true },
      { text: 'Kind des Zwielichts', expanded: true },
      { text: 'Riss zwischen den Welten', expanded: true },
      { text: 'Gezeichnete des Mondes', expanded: true },
    ],
    powerTagPool: [
      'verschwindet in den Schatten', 'sieht das Unsichtbare', 'spricht mit Toten', 'unverletzlich durch Stahl', 'kann sich verwandeln', 'spürt lebende Seelen', 'übersteht Feuer', 'bewegt Dinge ohne Berührung', 'Krallen oder Reißzähne', 'fließt durch Spalten', 'erscheint und verschwindet', 'flüstert Gedanken in andere', 'spürt böse Magie', 'liebt Dunkelheit',
      { text: 'sieht durch Glamour und Täuschung', expanded: true },
      { text: 'hört, was nicht gesagt wird', expanded: true },
      { text: 'erregt keine Aufmerksamkeit, wenn sie es nicht will', expanded: true },
      { text: 'findet den Weg zwischen Welten', expanded: true },
      { text: 'spürt Tode in der Nähe', expanded: true },
      { text: 'spricht die Sprache der anderen Seite', expanded: true },
      { text: 'hält sich in Räumen auf, die andere nicht sehen', expanded: true },
      { text: 'beeinflusst Stimmungen durch bloße Anwesenheit', expanded: true },
      { text: 'löst sich kurz aus dem Körper', expanded: true },
      { text: 'schläft nie, braucht es nicht', expanded: true },
    ],
    weaknessTagPool: [
      'gebannt durch Salz / Eisen / Sonne', 'gemieden von Mensch und Tier', 'angreifbar durch heiliges Symbol', 'gehasst von beiden Welten',
      { text: 'zu lange in der anderen Welt macht vergessen', expanded: true },
      { text: 'manche Menschen reagieren körperlich auf ihre Nähe', expanded: true },
      { text: 'hat keine Kontrolle, wenn der Mond voll ist', expanded: true },
      { text: 'verliert sich, wenn sie zu lange Menschliches spielt', expanded: true },
    ],
    questPool: [
      { title: 'Ich finde heraus, was ich wirklich bin.', description: 'Mein Spiegelbild gehorcht mir nicht ganz, mein Schatten flüstert. Es muss eine Antwort geben, und ich werde sie finden.' },
      { title: 'Ich finde meinen Platz unter den Menschen.', description: 'Ich bin nicht ganz von ihnen, doch ich bin auch nirgendwo sonst. Vielleicht gibt es einen Weg, dazwischen zu leben.' },
      { title: 'Ich bin meinem Wesen treu, koste es, was es wolle.', description: 'Mich zu verstecken ist eine Form von Tod. Ich werde sein, was ich bin, auch wenn die Welt es nicht erträgt.' },
      { title: 'Ich befreie mich von meinem Bann.', description: 'Was an mir hängt, hängt nicht zu Recht. Ich werde es abschütteln, und sei es das Letzte, was ich tue.' },
      { title: 'Ich finde die, die mich so gemacht haben, wie ich bin.', description: 'Ich bin kein Zufall. Irgendwer oder irgendetwas hat mich zu dem gemacht, was ich bin. Ich werde ihnen gegenüberstehen.', expanded: true },
      { title: 'Ich lerne, in beiden Welten zu leben.', description: 'Lange habe ich zwischen ihnen gependelt. Vielleicht ist das kein Fehler, sondern eine Fähigkeit. Ich werde es herausfinden.', expanded: true },
      { title: 'Ich schütze jemanden, der mein Wesen akzeptiert.', description: 'Fast niemand tut das. Wer es tut, verdient alles, was ich zu geben habe.', expanded: true },
      { title: 'Ich bringe Frieden zwischen das Übernatürliche und das Sterbliche.', description: 'Beide Seiten fürchten sich. Ich stehe dazwischen. Vielleicht kann ich das nutzen, um etwas Bleibendes zu schaffen.', expanded: true },
    ]
  },

  Destiny: {
    type: 'Greatness',
    titleTagSuggestions: [
      'Erbin des Throns', 'Untergang der Welt', 'finde den Erzähler', 'Auserwählter der Götter', 'das letzte Licht', 'das Kind der Sterne',
      { text: 'Trägerin des alten Zeichens', expanded: true },
      { text: 'die, die den Riss schließt', expanded: true },
      { text: 'Prophezeite der Tiefe', expanded: true },
      { text: 'Kind zweier Zeitalter', expanded: true },
      { text: 'Erfüllerin des Vergessenen Wortes', expanded: true },
      { text: 'Schlusspunkt der Geschichte', expanded: true },
    ],
    powerTagPool: [
      'das Schicksal beschützt mich', 'Zeichen weisen den Weg', 'Verbündete erscheinen', 'Glück folgt meinen Schritten', 'wundersame Rettung', 'die Welt hört auf mich', 'Vorhersehung leitet mich', 'verborgene Helfer', 'Wege öffnen sich', 'Türen, die niemand öffnen sollte', 'mein Antlitz erkennt jeder', 'Bestimmung pulsiert in mir', 'Träume offenbaren Geheimnisse', 'unerschütterlicher Mut',
      { text: 'zieht die richtigen Menschen an', expanded: true },
      { text: 'die Welt schiebt sich subtil zurecht', expanded: true },
      { text: 'überlebt das, was sie nicht sollte', expanded: true },
      { text: 'findet Zeichen in allem, was andere für Zufall halten', expanded: true },
      { text: 'ihr Wort trägt Gewicht, das sie nicht erklären kann', expanded: true },
      { text: 'handelt richtig, auch ohne es zu wissen', expanded: true },
      { text: 'ihre Träume zeigen Wege, die noch nicht existieren', expanded: true },
      { text: 'anderen fällt es schwer, sich ihr zu widersetzen', expanded: true },
      { text: 'steht nach jedem Fall wieder auf', expanded: true },
      { text: 'die Sterne stehen, wenn sie handelt', expanded: true },
    ],
    weaknessTagPool: [
      'Feinde wollen mich verhindern', 'der Pfad ist eng', 'Hochmut verfolgt mich', 'andere fordern meinen Tod',
      { text: 'die Bestimmung fordert Opfer, die sie nicht freiwillig bringt', expanded: true },
      { text: 'zweifelt, ob die Prophezeiung echt ist', expanded: true },
      { text: 'wer Schicksal trägt, verliert Entscheidungsfreiheit', expanded: true },
      { text: 'zieht Feinde an, die sie nicht sucht', expanded: true },
    ],
    questPool: [
      { title: 'Ich erfülle, wozu ich geboren wurde.', description: 'Es ist alles in mir angelegt, ob ich es wollte oder nicht. Ich höre auf, mich zu wehren, und gehe den Weg.' },
      { title: 'Ich beweise, dass ich frei bin trotz meiner Bestimmung.', description: 'Sie sagen, mein Pfad sei vorgezeichnet. Ich werde ihnen zeigen, dass sie sich irren, mit jedem Schritt, den ich anders setze.' },
      { title: 'Ich rette die Welt vor dem, was kommt.', description: 'Andere sehen es nicht, oder sie wollen es nicht sehen. Aber das Unheil ist nahe, und ich stehe in seinem Weg.' },
      { title: 'Ich entdecke, wer mich auserwählt hat.', description: 'Diese Bestimmung kommt nicht aus dem Nichts. Hinter ihr steht jemand, und ich werde ihn finden, ob er das will oder nicht.' },
      { title: 'Ich entscheide, ob ich das Schicksal annehme oder ablehne.', description: 'Vielleicht bin ich die Auserwählte. Vielleicht ist das alles eine Lüge. Bevor ich handle, werde ich es wissen.', expanded: true },
      { title: 'Ich bereite die vor mir, die nach der Erfüllung kommen.', description: 'Wenn es getan ist, wird die Welt anders sein. Ich sorge dafür, dass jemand für das Danach vorbereitet ist.', expanded: true },
      { title: 'Ich verhindere die Prophezeiung, die meinen Untergang bedeutet.', description: 'Das Schicksal läuft auf etwas zu, das ich nicht will. Ich werde beweisen, dass man eine Prophezeiung brechen kann.', expanded: true },
      { title: 'Ich finde den anderen Teil der Prophezeiung, der mir fehlt.', description: 'Was ich weiß, ist ein Fragment. Das Ganze würde alles verändern. Ich werde es suchen, auch wenn die Suche gefährlich ist.', expanded: true },
    ]
  },

  Dominion: {
    type: 'Greatness',
    titleTagSuggestions: [
      'Herrin der Mark', 'Anführerin der Gilde', 'Lehnsherr von Stein', 'Königin des Tales', 'Befehlshaber der Wache',
      { text: 'Herrscherin des Zwielichtreiches', expanded: true },
      { text: 'Erbin einer Festung ohne Land', expanded: true },
      { text: 'Anführerin des Widerstands', expanded: true },
      { text: 'Regentin für ein minderjähriges Kind', expanded: true },
      { text: 'Herrscherin durch Geburt und Last', expanded: true },
      { text: 'Herrin der verbotenen Stadt', expanded: true },
    ],
    powerTagPool: [
      'Soldaten meines Reiches', 'Tribute aus dem Land', 'Banner und Wappen', 'Recht zu richten', 'Burg auf dem Berg', 'Räte und Berater', 'Steuereinnahmen', 'eingespielte Verwaltung', 'kennt die Adligen', 'Boten in jede Richtung', 'spricht für ein Volk', 'Recht auf Krieg', 'beste Spione weit und breit',
      { text: 'beherrscht das Gleichgewicht der Mächte', expanded: true },
      { text: 'kann legitimieren, was andere nicht können', expanded: true },
      { text: 'kennt die Grenzen ihres Reiches besser als jeder andere', expanded: true },
      { text: 'die Bevölkerung ist ihr ergeben', expanded: true },
      { text: 'tritt Krisen entgegen, bevor sie ausbrechen', expanded: true },
      { text: 'regiert durch Stärke, nicht durch Furcht', expanded: true },
      { text: 'kennt jeden Nachbarn und seine Pläne', expanded: true },
      { text: 'kann eine Armee in Tagen bewegen', expanded: true },
      { text: 'hat Reserven, die niemand kennt', expanded: true },
      { text: 'ihr Wort macht aus einem Verdächtigen einen Schuldigen', expanded: true },
    ],
    weaknessTagPool: [
      'der Thron wird begehrt', 'Schulden gegenüber Mächtigen', 'Aufstand gärt', 'einsam an der Spitze',
      { text: 'das Reich verlangt Opfer, die sie persönlich zahlt', expanded: true },
      { text: 'ein Verräter sitzt im inneren Kreis', expanded: true },
      { text: 'jede Schwäche wird ausgenutzt', expanded: true },
      { text: 'Entscheidungen für viele sind Entscheidungen ohne Gewissen', expanded: true },
    ],
    questPool: [
      { title: 'Ich vergrößere mein Reich.', description: 'Was ich habe, ist nicht genug. Mein Schatten soll länger werden, und stärker, bis er die Welt berührt.' },
      { title: 'Ich beschütze mein Land vor allen Feinden.', description: 'Diese Erde gehört zu mir, und ich zu ihr. Wer sie bedroht, bedroht alles, wofür ich stehe.' },
      { title: 'Ich bin der gerechte Herrscher, den dieses Land verdient.', description: 'Vor mir gab es Tyrannen oder Schwächlinge. Ich werde anders sein, und mein Volk wird es spüren.' },
      { title: 'Ich finde heraus, wer mich verraten hat.', description: 'Es war jemand, dem ich vertraute. Solange dieser Name nicht ans Licht kommt, kann ich niemandem mehr glauben.' },
      { title: 'Ich baue das Reich auf, das es verdient, weiterzubestehen.', description: 'Was ich aufgebaut habe, soll nicht mit mir enden. Ich lege Grundsteine für die Herrschaft nach mir.', expanded: true },
      { title: 'Ich beende einen Krieg, der das Land seit Generationen zerstört.', description: 'Die Toten liegen auf beiden Seiten. Es muss enden, und jemand muss die Last des Friedens tragen.', expanded: true },
      { title: 'Ich setze Recht durch, das mich selbst treffen könnte.', description: 'Das Gesetz gilt für alle, oder es gilt für niemanden. Das werde ich beweisen, auch wenn es mich kostet.', expanded: true },
      { title: 'Ich gebe das Reich an die zurück, denen es gehört.', description: 'Ich habe zu lange regiert. Es ist Zeit, Macht abzugeben, bevor sie mich korrumpiert, wenn es nicht schon zu spät ist.', expanded: true },
    ]
  },

  Mastery: {
    type: 'Greatness',
    titleTagSuggestions: [
      'legendärer Schmied', 'Meister der Klinge', 'Erbauer der Welten', 'Königin der Stimme', 'unangefochtene Heilerin',
      { text: 'Weber des Lebens', expanded: true },
      { text: 'letzte ihrer Schule', expanded: true },
      { text: 'Meisterin der verbotenen Kunst', expanded: true },
      { text: 'Lehrmeisterin ohne Schüler', expanded: true },
      { text: 'Legende zu Lebzeiten', expanded: true },
      { text: 'vollendete Navigatorin', expanded: true },
    ],
    powerTagPool: [
      'Werkzeuge eines Meisters', 'gilt als Legende', 'Schüler aus aller Welt', 'kann das Unmögliche schaffen', 'kennt jede Variante', 'meisterhafte Kontrolle', 'eine Werkstatt mit eigenem Namen', 'Werke werden Jahrhunderte überdauern', 'andere Meister suchen Rat', 'andere Disziplinen ähnlich beherrscht', 'unverwechselbarer Stil', 'kann keinen Wettkampf verlieren', 'geheime Techniken',
      { text: 'überblickt die Geschichte der Disziplin vollständig', expanded: true },
      { text: 'ihre Technik hat keinen Namen, weil noch niemand sie beschrieben hat', expanded: true },
      { text: 'lehrt mit einem Blick, wo andere Worte brauchen', expanded: true },
      { text: 'verbessert das Werk anderer, ohne es zu stehlen', expanded: true },
      { text: 'erkennt Fehler, die noch keiner gemacht hat', expanded: true },
      { text: 'baut auf dem auf, was war, und geht darüber hinaus', expanded: true },
      { text: 'kennt die Seele eines Materials, bevor sie es berührt', expanded: true },
      { text: 'kann jede Technik in jeder Umgebung anpassen', expanded: true },
      { text: 'ihr Ruf öffnet Türen, die für andere verschlossen sind', expanded: true },
      { text: 'sieht in einem Stück, was Jahre gebraucht hat', expanded: true },
    ],
    weaknessTagPool: [
      'gefährdet durch Neid', 'jeder will von mir lernen', 'erwartet zu hohe Standards', 'wird zur Geisel meiner Größe',
      { text: 'niemand auf ihrer Ebene ist mehr da', expanded: true },
      { text: 'verlangt von sich selbst, was von anderen unzumutbar wäre', expanded: true },
      { text: 'kann Mittelmaß physisch nicht ertragen', expanded: true },
      { text: 'der Ruhm bringt Feinde, die sie nicht sah', expanded: true },
    ],
    questPool: [
      { title: 'Ich erschaffe das Meisterwerk meines Lebens.', description: 'Alles bisher war nur Üben. Das Werk, das mich überdauert, liegt noch vor mir, und ich weiß, dass es kommt.' },
      { title: 'Ich gebe meine Kunst an die nächste Generation weiter.', description: 'Was ich kann, ist zu kostbar, um zu verschwinden. Ich finde die, die würdig sind, und übergebe es ihnen.' },
      { title: 'Ich verändere die Welt mit meiner Kunst.', description: 'Mein Werk soll mehr sein als schön. Es soll etwas verschieben, etwas öffnen, das vorher zu war.' },
      { title: 'Ich finde jemanden, der mich übertrifft.', description: 'An der Spitze ist es einsam. Erst wenn jemand kommt, der mich fordert, bin ich wirklich am Leben.' },
      { title: 'Ich rette, was von meiner Schule noch zu retten ist.', description: 'Wir sterben aus. Die letzten Schüler sind gegangen oder gefallen. Ich bin die Letzte, die es noch weiß.', expanded: true },
      { title: 'Ich beweise, dass meine Kunst keinen Krieg braucht.', description: 'Andere nutzen das, was ich kann, um zu zerstören. Ich werde zeigen, dass es dafür nicht gedacht war.', expanded: true },
      { title: 'Ich vollende das Werk, das mein Lehrer nicht abschließen konnte.', description: 'Er starb mit halbfertiger Hand. Ich kenne den Plan. Ich werde es zu Ende bringen, als wären es seine Hände.', expanded: true },
      { title: 'Ich finde die letzte Technik, die ich noch nicht beherrsche.', description: 'Es gibt eine. Ich spüre es. Irgendwo dort draußen wartet sie, und wenn ich sie finde, bin ich fertig.', expanded: true },
    ]
  },

  Monstrosity: {
    type: 'Greatness',
    titleTagSuggestions: [
      'Drachenwurm', 'Sturmtitan', 'Nebelhydra', 'das Größenwesen aus dem See', 'der Wandelnde Wald',
      { text: 'Urblut aus dem Gebirge', expanded: true },
      { text: 'das letzte seiner Art', expanded: true },
      { text: 'sterblicher Rest eines Gottes', expanded: true },
      { text: 'das Schlafende unter dem Eis', expanded: true },
      { text: 'Titan des Vergessenen Zeitalters', expanded: true },
      { text: 'Wächter der Schwelle', expanded: true },
    ],
    powerTagPool: [
      'enorme Größe', 'flügelschlag wie Sturm', 'unverletzbare Haut', 'magische Aura der Furcht', 'unstillbarer Hunger', 'Schwanz, der Bäume fällt', 'Atem aus Feuer / Eis / Säure', 'Schreckenskreis um mich', 'unergründlicher Blick', 'Diener gehorchen mir', 'übermächtige Stärke', 'rufe Stürme', 'gigantische Schritte',
      { text: 'spricht eine Sprache, die die Erde versteht', expanded: true },
      { text: 'sein Auftreten verändert das Wetter', expanded: true },
      { text: 'altert nicht, vergisst nicht', expanded: true },
      { text: 'sein Schrei lässt Strukturen zittern', expanded: true },
      { text: 'spürt den Tod auf Meilen', expanded: true },
      { text: 'zieht Tiere an, die ihm dienen', expanded: true },
      { text: 'kann sich auf das Maß eines Menschen verkleinern', expanded: true },
      { text: 'sein Blut hat Wirkung, die keine Magie kennt', expanded: true },
      { text: 'verlässt nie das Territorium, das ihm gehört', expanded: true },
      { text: 'sein Schlaf bewirkt Dinge in der Welt', expanded: true },
    ],
    weaknessTagPool: [
      'eine verwundbare Stelle', 'jagdwürdig in den Augen vieler', 'zu groß für menschliche Welt', 'der Hunger erschüttert mich',
      { text: 'der Schlaf kommt und er kann nichts dagegen tun', expanded: true },
      { text: 'Menschen reagieren mit Panik, auch wenn er es nicht will', expanded: true },
      { text: 'ein alter Name hat Macht über ihn', expanded: true },
      { text: 'die Zeit bewegt sich anders um ihn', expanded: true },
    ],
    questPool: [
      { title: 'Ich finde meinesgleichen.', description: 'Irgendwo da draußen müssen andere sein wie ich. Bis ich sie gefunden habe, bin ich allein in der Welt.' },
      { title: 'Ich akzeptiere mein Wesen.', description: 'So lange habe ich mit dem gerungen, was ich bin. Es ist Zeit, damit zu leben, statt davor zu fliehen.' },
      { title: 'Ich beschütze meine Brut, koste es, was es wolle.', description: 'Sie sind mein und nur mein. Wer sie anrührt, kennt meine ganze Macht, und keine Gnade.' },
      { title: 'Ich kehre zur menschlichen Form zurück.', description: 'Das, was ich war, fehlt mir mehr, als ich es ertrage. Ich werde einen Weg zurück finden, oder daran zugrunde gehen.' },
      { title: 'Ich finde die, die mich so gemacht haben, wie ich bin.', description: 'Das war kein Unfall der Natur. Irgendwer hat das getan. Ich werde sie finden, und dann werden wir reden.', expanded: true },
      { title: 'Ich verteidige mein Territorium gegen das, was es bedroht.', description: 'Alles, was hier lebt, lebt unter meinem Schutz. Das ist keine Entscheidung, das ist, wer ich bin.', expanded: true },
      { title: 'Ich finde einen Weg, mit Menschen zu existieren, ohne Furcht.', description: 'Ich habe es satt, Schrecken zu sein. Irgendwo gibt es einen Weg, nebeneinander zu stehen, nicht gegenüber.', expanded: true },
      { title: 'Ich überlebe, bis die Welt mich wieder braucht.', description: 'Es gab eine Zeit, in der Wesen wie ich einen Platz hatten. Diese Zeit kommt wieder. Ich werde da sein.', expanded: true },
    ]
  },

  Companion: {
    type: 'Variable Might',
    titleTagSuggestions: [
      'Schwertbande', 'imposanter Wolfshund', 'Schutzgeist', 'frecher Pixie', 'Falke meiner Mutter', 'Beschwörter Geist',
      { text: 'alter Freund, treuer Strolch', expanded: true },
      { text: 'stummer Wächter', expanded: true },
      { text: 'Geist des Hauses', expanded: true },
      { text: 'wilde Katze mit Verstand', expanded: true },
      { text: 'Veteranenbande ohne Hauptmann', expanded: true },
      { text: 'Elementargeist auf Probe', expanded: true },
    ],
    powerTagPool: [
      'imposanter Wolfshund', 'spürt feindliche Absichten', 'Bande Schwertkämpfer', 'kämpft mit mir Schulter an Schulter', 'gehorcht jedem Befehl', 'Ablenkung mit Verve', 'unsichtbarer Schutzgeist', 'flüstert Warnungen', 'zerstreut die Wache', 'läuft schneller als mein Pferd', 'schmuggelt Botschaften', 'tröstet mich in der Nacht', 'unfehlbare Spürnase', 'Familie an meiner Seite',
      { text: 'handelt eigenständig im richtigen Moment', expanded: true },
      { text: 'hält Wache, ohne zu schlafen', expanded: true },
      { text: 'findet den Weg, wenn ich ihn verloren habe', expanded: true },
      { text: 'lockt Feinde vom richtigen Pfad', expanded: true },
      { text: 'erinnert mich daran, warum ich kämpfe', expanded: true },
      { text: 'versteckt sich perfekt und beobachtet', expanded: true },
      { text: 'rettet mich, wenn ich mich nicht retten kann', expanded: true },
      { text: 'kennt meine Grenzen besser als ich', expanded: true },
      { text: 'versteht meine Zeichen ohne Worte', expanded: true },
      { text: 'bringt mir, was ich suche, ohne Erklärung', expanded: true },
    ],
    weaknessTagPool: [
      'gerät leicht in Gefahr', 'lärmig und unbeherrscht', 'kann mich verlassen', 'beschützt nur mich',
      { text: 'handelt manchmal ohne Anweisung falsch', expanded: true },
      { text: 'Feinde kennen die Schwäche für den Begleiter', expanded: true },
      { text: 'braucht mehr Fürsorge als ich geben kann', expanded: true },
      { text: 'wird als Schwäche gesehen', expanded: true },
    ],
    questPool: [
      { title: 'Ich beschütze meinen Begleiter um jeden Preis.', description: 'Sie sind das, was meinen Weg erträglich macht. Ohne sie geht es nicht weiter, und das wissen wir beide.' },
      { title: 'Ich erfülle einen Auftrag mit meinem Begleiter.', description: 'Was wir uns vorgenommen haben, schaffen wir nur zusammen. Allein wäre keiner von uns genug.' },
      { title: 'Ich bringe ihn / sie heim.', description: 'Wir wurden auseinandergerissen, doch ich vergesse den Weg nicht. Ich bringe sie zurück, woher wir kamen.' },
      { title: 'Ich befreie ihn / sie aus dem Bann.', description: 'Das, was an meinem Begleiter hängt, gehört da nicht hin. Ich werde es lösen, mit jedem Mittel, das ich finde.' },
      { title: 'Ich finde meinen Begleiter, der verloren gegangen ist.', description: 'Er / sie ist weg, und jeder Tag ohne ist ein Tag zu viel. Ich werde jeden Stein umdrehen.', expanded: true },
      { title: 'Ich beweise, dass mein Begleiter kein Monster ist.', description: 'Alle sehen etwas Gefährliches. Ich sehe das, was ich kenne. Ich werde es ihnen zeigen.', expanded: true },
      { title: 'Ich lasse meinen Begleiter gehen, wenn es an der Zeit ist.', description: 'Manche Bindungen haben ein Ende. Ich werde es erkennen und ihn / sie ziehen lassen, auch wenn es wehtut.', expanded: true },
      { title: 'Ich finde heraus, was meinen Begleiter so gemacht hat, wie er / sie ist.', description: 'Es gibt eine Geschichte dahinter. Ich werde sie kennen, damit ich besser für ihn / sie da sein kann.', expanded: true },
    ]
  },

  Magic: {
    type: 'Variable Might',
    titleTagSuggestions: [
      'Hexe der Wälder', 'Sturmrufer', 'Heiler der Götter', 'Banner der Geister', 'rituelle Zauberin', 'Alchemistin',
      { text: 'Runenschreiberin', expanded: true },
      { text: 'Beschwörerin des Wassers', expanded: true },
      { text: 'Traumwirkerin', expanded: true },
      { text: 'Zauberin des Übergangs', expanded: true },
      { text: 'Hüterin des Gleichgewichts', expanded: true },
      { text: 'Sprecherin der vergessenen Sprache', expanded: true },
    ],
    powerTagPool: [
      'kleines Zauberwerk', 'Bannkreis ziehen', 'spricht alte Worte', 'verflucht den Feind', 'segnet die Verbündeten', 'spricht mit Geistern', 'verwandelt sich in Tier', 'sieht durch Schleier', 'braut starke Tränke', 'schreibt mächtige Runen', 'beschwört kleine Wesen', 'Heilkräuter und Salben', 'Magieeisen erkennen', 'lenkt die Winde', 'hext Dinge in die Bewegung', 'flüstert in die Träume',
      { text: 'kennt die Grenze zwischen Magie und Natur', expanded: true },
      { text: 'liest die Magie anderer wie einen Text', expanded: true },
      { text: 'sieht Verbindungen zwischen Personen', expanded: true },
      { text: 'biegt Zufall in die gewünschte Richtung', expanded: true },
      { text: 'kennt Schutzzauber, die Jahrhunderte halten', expanded: true },
      { text: 'hebt Flüche, wenn die Bedingungen stimmen', expanded: true },
      { text: 'spricht den Wald an und er antwortet', expanded: true },
      { text: 'kann Magie aus Objekten lesen', expanded: true },
      { text: 'kennt die Regeln der Magie besser als die, die sie brechen', expanded: true },
      { text: 'erzeugt Licht, das tröstet', expanded: true },
    ],
    weaknessTagPool: [
      'erschöpft durch Magie', 'gehasst und gehetzt', 'verlangt einen Preis', 'unkontrollierbare Nebenwirkungen',
      { text: 'Magie macht sie für andere unlesbar', expanded: true },
      { text: 'stärkere Magie zieht stärkere Aufmerksamkeit', expanded: true },
      { text: 'ihr Körper zahlt den Preis für das, was ihre Magie tut', expanded: true },
      { text: 'bestimmte Zauber vergisst sie nach dem Wirken', expanded: true },
    ],
    questPool: [
      { title: 'Ich verstehe, woher meine Magie wirklich kommt.', description: 'Sie kommt aus mir, aber nicht nur. Ich folge ihr zurück zu ihrer Quelle, auch wenn sie mich erschreckt.' },
      { title: 'Ich nutze meine Magie nur für Würdiges.', description: 'Was ich kann, ist gefährlich. Ich werde nicht zulassen, dass es sich verschwendet oder beschmutzt.' },
      { title: 'Ich befreie die, denen ich Unrecht tat.', description: 'Meine Magie hat Schaden angerichtet, oft ohne dass ich es wollte. Ich werde diese Schuld abtragen, eine nach der anderen.' },
      { title: 'Ich finde einen Lehrer, der mich vollendet.', description: 'Allein komme ich nicht weiter. Irgendwo gibt es einen, der weiß, was ich brauche, und ich werde ihn finden.' },
      { title: 'Ich versiegele das, was ich geöffnet habe.', description: 'Ein Zauber, ein Tor, ein Fluch: ich habe etwas losgetreten, das sich nicht von selbst auflöst. Ich muss es zurückholen.', expanded: true },
      { title: 'Ich lerne, Magie zu verwenden, ohne ihren Preis zu ignorieren.', description: 'Die Kraft ist real, und der Preis auch. Ich höre auf, das zweite zu verdrängen.', expanded: true },
      { title: 'Ich zerstöre das alte Wissen, das zu gefährlich ist, um zu existieren.', description: 'Ich kenne ein Ritual, das nicht gelehrt werden darf. Ich werde dafür sorgen, dass es mit mir endet.', expanded: true },
      { title: 'Ich beweise, dass Magie kein Fluch ist.', description: 'Alle, die mich fürchten, fürchten, was sie nicht verstehen. Ich werde ihnen zeigen, was es wirklich ist.', expanded: true },
    ]
  },

  Possessions: {
    type: 'Variable Might',
    titleTagSuggestions: [
      'handgefertigte Panflöte', 'verborgene Dolche', 'Pferd und Rüstung', 'Brief des Fürsten', 'Kette aus Gold', 'mein Werkzeugkasten',
      { text: 'Truhe mit fremden Münzen', expanded: true },
      { text: 'geerbt und zu groß', expanded: true },
      { text: 'Ausrüstung der toten Kompanie', expanded: true },
      { text: 'eine Karte, die mehr zeigt als gedacht', expanded: true },
      { text: 'das Letzte, was sie in der Heimat mitnahm', expanded: true },
      { text: 'Inventar eines Abenteurers, der nicht zurückkam', expanded: true },
    ],
    powerTagPool: [
      'meisterhaft geschmiedete Klinge', 'reich gefüllte Reisetasche', 'Pferd, das mir gehorcht', 'verborgene Dolche', 'verziertes Wams', 'Werkzeug für jeden Fall', 'Brief mit Siegel', 'Kette von Wert', 'gut gewartete Rüstung', 'silberne Pfeile', 'Reisekarten', 'wertvoller Schmuck', 'Truhe mit Wertsachen', 'getarnter Reisemantel',
      { text: 'das Richtige für unwahrscheinliche Situationen', expanded: true },
      { text: 'gut gepflegt und immer einsatzbereit', expanded: true },
      { text: 'kennt den Wert jedes Gegenstands auf den Pfennig', expanded: true },
      { text: 'hat immer ein Ersatzteil', expanded: true },
      { text: 'tauscht klug und verliert nie', expanded: true },
      { text: 'findet das Richtige im Gepäck, wenn es gebraucht wird', expanded: true },
      { text: 'schleppt nichts Unnötiges', expanded: true },
      { text: 'hat eine Waffe verborgen, die niemand sucht', expanded: true },
      { text: 'kennt, was sie hat, bis auf den letzten Nagel', expanded: true },
      { text: 'eine Sprache, die ihre Ausrüstung sprechen lässt', expanded: true },
    ],
    weaknessTagPool: [
      'verletzlich gegen Diebe', 'braucht Pflege', 'auffällig im Wert', 'Bindung an einen Ort',
      { text: 'wer von dem Besitz weiß, will ihn', expanded: true },
      { text: 'der Besitz erinnert an Verlust', expanded: true },
      { text: 'kann ohne den Besitz nur halb so viel', expanded: true },
      { text: 'gibt zu viel aus, wenn sie zu viel hat', expanded: true },
    ],
    questPool: [
      { title: 'Ich verbessere mein Werkzeug, bis es perfekt ist.', description: 'Was ich besitze, ist mehr als nur Material. Es ist Teil von mir, und es soll werden, was es sein kann.' },
      { title: 'Ich behalte das Erbstück um jeden Preis.', description: 'Es gehörte zu denen vor mir, und es ist alles, was mir von ihnen blieb. Ich gebe es nicht her.' },
      { title: 'Ich finde das fehlende Stück meiner Sammlung.', description: 'Etwas fehlt, und solange es fehlt, bin ich nicht fertig. Ich werde nicht ruhen, bis es bei mir ist.' },
      { title: 'Ich teile, was ich habe, gerecht aus.', description: 'Was mir zugefallen ist, gehört nicht mir allein. Ich finde den richtigen Weg, es zu verteilen.' },
      { title: 'Ich besorge das, was für eine unmögliche Aufgabe gebraucht wird.', description: 'Es gibt kein "nicht erhältlich". Es gibt nur "noch nicht gefunden". Ich finde es.', expanded: true },
      { title: 'Ich gebe meinen wertvollsten Besitz hin, wenn die Zeit kommt.', description: 'Ich weiß, dass es kommen wird, dieser Moment, in dem das Richtige ist, loszulassen. Ich werde es tun.', expanded: true },
      { title: 'Ich stelle das Verlorene wieder her, das nicht ersetzt werden kann.', description: 'Es ist weg, und niemand glaubt, dass man es zurückbekommt. Ich glaube das auch nicht. Ich versuche es trotzdem.', expanded: true },
      { title: 'Ich finde heraus, woher das Erbstück wirklich kommt.', description: 'Jemand gab es mir mit Schweigen. Das Schweigen hat mich seit Jahren beschäftigt. Es ist Zeit, Antworten zu bekommen.', expanded: true },
    ]
  }
};

const TYPE_TO_THEMEBOOKS = {
  'Origin': ['Circumstance', 'Devotion', 'Past', 'People', 'Personality', 'Skill or Trade', 'Trait'],
  'Adventure': ['Duty', 'Influence', 'Knowledge', 'Prodigious Ability', 'Relic', 'Uncanny Being'],
  'Greatness': ['Destiny', 'Dominion', 'Mastery', 'Monstrosity'],
  'Variable Might': ['Companion', 'Magic', 'Possessions']
};

const PHASES = [
  {
    id: 1, title: 'Stimmung & Welt', eyebrow: 'Phase 1 von 4',
    cards: [
      { title: 'Ein Hof am Waldrand bei Nebel', text: 'Stille zwischen den Bäumen, Rauch über dem Dach.', affinities: { 'Skill or Trade': 2, 'People': 1, 'Past': 1, 'Companion': 1 }, hooks: ['ländlich','wildnis','ruhig'] },
      { title: 'Eine zerstörte Burg, in der noch jemand wohnt', text: 'Die Mauern sind alt, aber der Rauch ist frisch.', affinities: { 'Past': 2, 'Circumstance': 2, 'Relic': 1, 'Dominion': 1 }, hooks: ['düster','vergangenheit','geheimnis'] },
      { title: 'Marktplatz, Geschrei, Diebesfinger', text: 'Das Leben drängt, der Geldbeutel ist leichter geworden.', affinities: { 'Skill or Trade': 2, 'Personality': 2, 'Influence': 1, 'Circumstance': 1 }, hooks: ['stadt','gewitzt','sozial'] },
      { title: 'Ein Buch, das niemand lesen sollte', text: 'Tinte, die sich noch bewegt. Die Seiten sind warm.', affinities: { 'Knowledge': 3, 'Magic': 1, 'Relic': 1, 'Past': 1 }, hooks: ['verboten','wissen','magisch'] },
      { title: 'Ein Schwur am Sterbebett', text: 'Hand auf dem fiebrigen Brustkorb, Worte, die binden.', affinities: { 'Devotion': 3, 'Duty': 2, 'Past': 1 }, hooks: ['eid','pflicht','schmerz'] },
      { title: 'Die offene Straße im Morgenlicht', text: 'Hinter mir die Heimat, vor mir das Unbekannte.', affinities: { 'Past': 2, 'Knowledge': 1, 'Personality': 1, 'Circumstance': 1 }, hooks: ['wanderer','frei','aufbruch'] },
      { title: 'Eine alte Schmiede mit Funkenflug', text: 'Jeder Hammerschlag hallt durch das Tal.', affinities: { 'Skill or Trade': 3, 'Mastery': 1, 'Possessions': 1 }, hooks: ['handwerk','feuer'] },
      { title: 'Ein Saal voll mit Adligen', text: 'Worte werden hier gewogen wie Gold und sind oft tödlicher.', affinities: { 'Circumstance': 2, 'Influence': 2, 'Personality': 1, 'Dominion': 1 }, hooks: ['hof','intrige','sozial'] },
      { title: 'Ein Kreis aus Kerzen, mitten in der Nacht', text: 'Die Schatten zucken im Takt einer fremden Sprache.', affinities: { 'Magic': 3, 'Knowledge': 1, 'Devotion': 1, 'Relic': 1 }, hooks: ['ritual','magisch','geheim'] }
    ]
  },
  {
    id: 2, title: 'Herkunft & Hintergrund', eyebrow: 'Phase 2 von 4',
    cards: [
      { title: 'Aus einer alten Familie mit Geheimnissen', text: 'Mein Name öffnet Türen und schließt andere für immer.', affinities: { 'People': 2, 'Past': 2, 'Circumstance': 1 }, hooks: ['adel','erbe','geheimnis'] },
      { title: 'Aufgewachsen unter Fremden', text: 'Niemand wusste, wer ich wirklich war. Vielleicht ich auch nicht.', affinities: { 'Past': 3, 'Circumstance': 1, 'Personality': 1 }, hooks: ['außenseiter','geheimnis'] },
      { title: 'Im Krieg verloren, im Frieden nicht heimisch', text: 'Ich kenne die Schlachtfelder besser als die Marktplätze.', affinities: { 'Past': 3, 'Duty': 1, 'Circumstance': 1 }, hooks: ['veteran','trauma','soldat'] },
      { title: 'Der einzige Überlebende meines Dorfes', text: 'Ich trage die Asche der Meinen mit mir. Niemand sonst tut es.', affinities: { 'Past': 3, 'People': 1, 'Devotion': 1 }, hooks: ['verlust','erinnerung'] },
      { title: 'Geboren in Reichtum, alles verloren', text: 'Heute kenne ich den Preis von Brot. Damals nicht.', affinities: { 'Circumstance': 3, 'Past': 1, 'Personality': 1 }, hooks: ['gefallen','adel'] },
      { title: 'Meine Familie übte ein Handwerk seit Generationen', text: 'Ich kannte den Geruch der Werkstatt, bevor ich laufen konnte.', affinities: { 'Skill or Trade': 3, 'People': 1, 'Possessions': 1 }, hooks: ['handwerk','tradition'] },
      { title: 'Adelige Erziehung, eigene Wege', text: 'Sie haben mir alles beigebracht, außer wer ich sein will.', affinities: { 'Circumstance': 2, 'Personality': 2, 'Knowledge': 1, 'Influence': 1 }, hooks: ['adel','rebellion'] },
      { title: 'Aufgewachsen mit ungewöhnlichen Lehrern', text: 'Was sie mir beibrachten, lernt man nicht in den Städten.', affinities: { 'Knowledge': 2, 'People': 1, 'Magic': 2 }, hooks: ['gelehrt','ungewöhnlich'] },
      { title: 'Ein Versprechen, das alles veränderte', text: 'Ein einziges Wort, gesagt zur falschen Zeit. Oder zur richtigen.', affinities: { 'Devotion': 3, 'Duty': 2 }, hooks: ['eid','wendepunkt'] },
      { title: 'Ich war nie wie die anderen', text: 'Schon als Kind wusste ich es. Andere wussten es auch.', affinities: { 'Trait': 3, 'Personality': 1, 'Uncanny Being': 1 }, hooks: ['anders','besonders'] }
    ]
  },
  {
    id: 3, title: 'Können & Wesen', eyebrow: 'Phase 3 von 4',
    cards: [
      { title: 'Ein altes Schwert, das nur ich führen kann', text: 'Es kennt meine Hand. Niemand sonst kann es heben.', affinities: { 'Relic': 3, 'Possessions': 1, 'Past': 1 }, hooks: ['relikt','waffe','erbe'] },
      { title: 'Ich verstehe, was Tiere sagen', text: 'Sie haben Geschichten. Manche sind Warnungen.', affinities: { 'Magic': 2, 'Trait': 1, 'Companion': 2, 'Uncanny Being': 1 }, hooks: ['tiere','magie','trait'] },
      { title: 'Ich lüge so gut, dass es manchmal wahr wird', text: 'Worte sind weicher als Stahl und schneiden tiefer.', affinities: { 'Skill or Trade': 2, 'Personality': 2, 'Influence': 1 }, hooks: ['list','sozial'] },
      { title: 'Ich kann Wunden flicken, die andere für tödlich halten', text: 'Hände, die wissen, wo der Faden hin muss.', affinities: { 'Skill or Trade': 2, 'Knowledge': 2, 'Magic': 1, 'Devotion': 1 }, hooks: ['heilung','handwerk'] },
      { title: 'Ich bin schneller, als jemand wie ich sein dürfte', text: 'Niemand sieht den Schritt kommen, der mich rettet.', affinities: { 'Trait': 3, 'Prodigious Ability': 2 }, hooks: ['gabe','gewandt'] },
      { title: 'Eine Magie, die ich nicht ganz beherrsche', text: 'Manchmal hilft sie. Manchmal lässt sie mich allein.', affinities: { 'Magic': 3, 'Uncanny Being': 1, 'Past': 1 }, hooks: ['magie','wild'] },
      { title: 'Ein Wesen, das mir folgt und mir gehört', text: 'Ich bin nicht allein, auch wenn es niemand sieht.', affinities: { 'Companion': 3, 'Magic': 1, 'Uncanny Being': 1 }, hooks: ['begleiter','geist'] },
      { title: 'Wissen über Dinge, die andere fürchten', text: 'Ich weiß, was im Schatten lauert. Sie wissen es nicht.', affinities: { 'Knowledge': 3, 'Past': 1, 'Magic': 1 }, hooks: ['gelehrt','dunkel'] },
      { title: 'Eine Bestimmung, die mir vorausgesagt wurde', text: 'Eine alte Frau sah es. Ich habe es lange nicht geglaubt.', affinities: { 'Destiny': 3, 'Past': 1 }, hooks: ['schicksal','prophezeiung'] },
      { title: 'Ich bin etwas anderes als ein Mensch', text: 'Mein Blut weiß es. Mein Spiegelbild auch.', affinities: { 'Uncanny Being': 3, 'Trait': 1, 'Monstrosity': 1 }, hooks: ['nicht-mensch','magisch'] }
    ]
  },
  {
    id: 4, title: 'Antrieb & Verwundbarkeit', eyebrow: 'Phase 4 von 4',
    cards: [
      { title: 'Ich suche jemanden, den ich verloren habe', text: 'Sein/ihr Name ist mein erstes Wort beim Aufwachen.', affinities: { 'Devotion': 2, 'Past': 2, 'Duty': 1 }, hooks: ['quest:suchen','liebe','vermisst'] },
      { title: 'Ich will herausfinden, was ich wirklich bin', text: 'Es gibt eine Antwort. Ich hoffe, ich kann mit ihr leben.', affinities: { 'Past': 2, 'Uncanny Being': 1, 'Trait': 1, 'Destiny': 1 }, hooks: ['quest:identität'] },
      { title: 'Ich vertraue niemandem mehr', text: 'Einmal war einmal zu oft.', affinities: { 'Personality': 2, 'Past': 2 }, hooks: ['weakness:misstrauen'] },
      { title: 'Mein Stolz ist mein größtes Problem', text: 'Ich weiß es. Und tue trotzdem nichts dagegen.', affinities: { 'Personality': 2, 'Mastery': 1, 'Circumstance': 1 }, hooks: ['weakness:stolz'] },
      { title: 'Ich habe einen Schwur zu erfüllen', text: 'Worte, die ich nicht zurücknehmen kann. Ich will es auch nicht.', affinities: { 'Devotion': 2, 'Duty': 3 }, hooks: ['quest:eid'] },
      { title: 'Ich will gegen ein Unrecht kämpfen', text: 'Solange es steht, schlafe ich nicht ruhig.', affinities: { 'Duty': 2, 'Devotion': 2, 'Influence': 1 }, hooks: ['quest:gerechtigkeit'] },
      { title: 'Ich habe eine Schuld zu begleichen', text: 'Sie steht in mir wie ein Stein. Eines Tages werfe ich ihn.', affinities: { 'Past': 3, 'Duty': 1 }, hooks: ['quest:schuld'] },
      { title: 'Ich will herausfinden, was hinter dem Nebel liegt', text: 'Andere drehen um. Ich gehe weiter.', affinities: { 'Knowledge': 2, 'Past': 1, 'Destiny': 1, 'Personality': 1 }, hooks: ['quest:erkenntnis'] }
    ]
  }
];
