/* =====================================================
   phases_patch.js — Einzelner Kartenstapel (40 Karten)
   Keine Phasen mehr — ein gemischter Stapel.
   hooks: thematische Schlagworte (Swipe-Bias). Kanonisches Vokabular:
   adel, außenseiter, geheimnis, magie, wissen, handwerk, glaube, kampf,
   natur, stadt, verlust, macht, fahrend, schicksal
   examples: 2-3 konkrete Helden-/Szenen-Skizzen (Inspiration auf der Swipe-Karte).
===================================================== */
(function() {
  var newCards = [
    // Welt & Atmosphäre
    { title: 'Ein Hof am Waldrand bei Nebel', text: 'Stille zwischen den Bäumen, Rauch über dem Dach.', affinities: { 'Skill or Trade': 2, 'People': 2, 'Companion': 1 }, hooks: ['natur','geheimnis'], examples: ['eine zurückgezogene Kräuterheilerin','ein Förster mit treuem Wolf','ein Bauernsohn mit Zweitem Gesicht'] },
    { title: 'Eine zerstörte Burg, in der noch jemand wohnt', text: 'Die Mauern sind alt, aber der Rauch ist frisch.', affinities: { 'Circumstance': 2, 'Relic': 1, 'Dominion': 2 }, hooks: ['geheimnis','verlust','macht'], examples: ['der letzte Erbe des Geschlechts','eine Hüterin des verfluchten Throns','Heimkehr zur Ruine der Ahnen'] },
    { title: 'Marktplatz, Geschrei, Diebesfinger', text: 'Das Leben drängt, der Geldbeutel ist leichter geworden.', affinities: { 'Skill or Trade': 2, 'Personality': 2, 'Influence': 1 }, hooks: ['stadt'], examples: ['ein flinker Gassendieb','eine redegewandte Marktbetrügerin','ein Geldverleiher mit vielen Schulden'] },
    { title: 'Ein Buch, das niemand lesen sollte', text: 'Tinte, die sich noch bewegt. Die Seiten sind warm.', affinities: { 'Knowledge': 3, 'Magic': 1, 'Relic': 1 }, hooks: ['wissen','geheimnis','magie'], examples: ['eine heimliche Beschwörerin','ein neugieriger Klosterschreiber','der Dieb des verbotenen Folianten'] },
    { title: 'Ein Schwur am Sterbebett', text: 'Hand auf dem fiebrigen Brustkorb, Worte, die binden.', affinities: { 'Devotion': 3, 'Duty': 2 }, hooks: ['glaube','verlust'], examples: ['ein eidgebundener Leibwächter','eine rachsüchtige Tochter','Schwur an den toten Bruder'] },
    { title: 'Eine alte Schmiede mit Funkenflug', text: 'Jeder Hammerschlag hallt durch das Tal.', affinities: { 'Skill or Trade': 3, 'Mastery': 1, 'Possessions': 1 }, hooks: ['handwerk'], examples: ['ein meisterlicher Waffenschmied','eine Schmiedin mit verfluchtem Hammer','der Lehrling übernimmt die Esse'] },
    { title: 'Ein Saal voll mit Adligen', text: 'Worte werden hier gewogen wie Gold und sind oft tödlicher.', affinities: { 'Circumstance': 2, 'Influence': 2, 'Dominion': 1 }, hooks: ['adel','macht'], examples: ['ein intriganter Hofberater','eine maskierte Spionin am Fest','der entehrte Baron sucht Verbündete'] },
    { title: 'Ein Kreis aus Kerzen, mitten in der Nacht', text: 'Die Schatten zucken im Takt einer fremden Sprache.', affinities: { 'Magic': 3, 'Knowledge': 1, 'Devotion': 1 }, hooks: ['magie','geheimnis'], examples: ['eine verbotene Ritualmagierin','ein Gelehrter dunkler Sprachen','die Beschwörung gerät außer Kontrolle'] },
    { title: 'Das Rumpeln tief unter der alten Erde', text: 'Es schläft schon sehr lange. Aber irgendetwas deutet darauf hin, dass es aufwacht.', affinities: { 'Monstrosity': 3, 'Destiny': 2 }, hooks: ['schicksal','geheimnis'], examples: ['ein erwachter Blutmagier','eine Wächterin uralter Siegel','das Beben spaltet den Bergstollen'] },
    { title: 'Eine Meisterin, die keine Worte braucht', text: 'Ich sah sie einmal arbeiten. Ich weiß jetzt, was ich nie erreichen werde.', affinities: { 'Mastery': 3, 'Prodigious Ability': 2 }, hooks: ['handwerk'], examples: ['eine schweigende Klingenschmiedin','ein verstummter Bogenmeister','ihre Hände lehren ohne Worte'] },
    // Herkunft & Hintergrund
    { title: 'Aus einer alten Familie mit Geheimnissen', text: 'Mein Name öffnet Türen und schließt andere für immer.', affinities: { 'People': 2, 'Past': 1, 'Dominion': 1, 'Circumstance': 1 }, hooks: ['adel','geheimnis'], examples: ['eine verstoßene Erbin','ein letzter Spross des Hauses','der Siegelring eines toten Geschlechts'] },
    { title: 'Aufgewachsen unter Fremden', text: 'Niemand wusste, wer ich wirklich war. Vielleicht ich auch nicht.', affinities: { 'Past': 1, 'Circumstance': 2, 'Personality': 1, 'Influence': 1 }, hooks: ['außenseiter','verlust'], examples: ['ein heimatloses Findelkind','eine Fremde unter Fremden','ein Kind ohne wahren Namen'] },
    { title: 'Im Krieg verloren, im Frieden nicht heimisch', text: 'Ich kenne die Schlachtfelder besser als die Marktplätze.', affinities: { 'Past': 1, 'Duty': 2, 'Influence': 1 }, hooks: ['kampf','verlust'], examples: ['ein heimkehrender Söldner','eine narbige Veteranin','verlorene Augen über dem Marktplatz'] },
    { title: 'Der einzige Überlebende meines Dorfes', text: 'Ich trage die Asche der Meinen mit mir. Niemand sonst tut es.', affinities: { 'Past': 1, 'People': 2, 'Devotion': 1, 'Destiny': 1 }, hooks: ['verlust','glaube'], examples: ['ein aschetragender Rächer','die letzte Beterin ihres Dorfes','er flüstert die Namen der Toten'] },
    { title: 'Meine Familie übte ein Handwerk seit Generationen', text: 'Ich kannte den Geruch der Werkstatt, bevor ich laufen konnte.', affinities: { 'Skill or Trade': 3, 'People': 1, 'Possessions': 1 }, hooks: ['handwerk'], examples: ['eine junge Waffenschmiedin','ein Erbe der alten Werkstatt','der Geruch von Glut und Eisen'] },
    { title: 'Adelige Erziehung, eigene Wege', text: 'Sie haben mir alles beigebracht, außer wer ich sein will.', affinities: { 'Circumstance': 2, 'Personality': 2, 'Influence': 1 }, hooks: ['adel','außenseiter'], examples: ['eine entlaufene Baronesse','ein rebellischer Höfling','sie wirft das Wappen fort'] },
    { title: 'Aufgewachsen mit ungewöhnlichen Lehrern', text: 'Was sie mir beibrachten, lernt man nicht in den Städten.', affinities: { 'Knowledge': 2, 'Magic': 2, 'Trait': 1 }, hooks: ['wissen','magie'], examples: ['eine heimliche Beschwörerin','Schüler eines Mooshexers','verbotene Runen gelernt'] },
    { title: 'Ich war nie wie die anderen', text: 'Schon als Kind wusste ich es. Andere wussten es auch.', affinities: { 'Trait': 3, 'Personality': 1, 'Uncanny Being': 1 }, hooks: ['außenseiter','schicksal'], examples: ['ein gezeichneter Wechselbalg','Kind mit zwei Schatten','die gemiedene Seherin'] },
    { title: 'Ich war für etwas Großes vorgesehen', text: 'Die Alten sahen es. Ich weigerte mich, es zu glauben.', affinities: { 'Destiny': 3, 'Dominion': 1 }, hooks: ['schicksal','macht'], examples: ['der widerwillige Auserwählte','eine geflohene Thronerbin','Prophezeiung auf der Stirn'] },
    { title: 'Ich habe etwas Wichtiges geerbt, das mich verfolgt', text: 'Es war ein Segen, sagten sie. Der Preis wurde nicht genannt.', affinities: { 'Relic': 3, 'Possessions': 2 }, hooks: ['geheimnis','schicksal'], examples: ['Trägerin eines fluchbeladenen Rings','ein verfolgter Erbe','das Amulett flüstert nachts'] },
    // Können & Wesen
    { title: 'Ein altes Schwert, das nur ich führen kann', text: 'Es kennt meine Hand. Niemand sonst kann es heben.', affinities: { 'Relic': 2, 'Possessions': 1, 'Mastery': 1 }, hooks: ['kampf','schicksal'], examples: ['ein verfemter Klingenträger','die letzte Schwertmeisterin','Hand am bindenden Stahl'] },
    { title: 'Ich verstehe, was Tiere sagen', text: 'Sie haben Geschichten. Manche sind Warnungen.', affinities: { 'Magic': 2, 'Companion': 2, 'Trait': 1 }, hooks: ['natur','magie'], examples: ['eine Hüterin der Wälder','Junge mit dem Rabenbund','Wolf warnt vor Hinterhalt'] },
    { title: 'Ich kann Wunden flicken, die andere nicht können', text: 'Hände, die wissen, wo der Faden hin muss.', affinities: { 'Skill or Trade': 2, 'Knowledge': 2, 'Devotion': 1 }, hooks: ['handwerk','glaube'], examples: ['eine wandernde Wundnäherin','der gläubige Feldscher','Hände schließen tiefe Risse'] },
    { title: 'Ich bin schneller, als jemand wie ich sein dürfte', text: 'Niemand sieht den Schritt kommen, der mich rettet.', affinities: { 'Trait': 3, 'Prodigious Ability': 2 }, hooks: ['schicksal'], examples: ['ein blitzschneller Schnitter','die unfassbare Diebin','Schritt schneller als Pfeile'] },
    { title: 'Eine Magie, die ich nicht ganz beherrsche', text: 'Manchmal hilft sie. Manchmal lässt sie mich allein.', affinities: { 'Magic': 3, 'Uncanny Being': 1 }, hooks: ['magie'], examples: ['eine ungelernte Funkenmagierin','ein verfluchter Wahrsager','Zauber misslingt im Kampf'] },
    { title: 'Ein Wesen, das mir folgt und mir gehört', text: 'Ich bin nicht allein, auch wenn es niemand sieht.', affinities: { 'Companion': 3, 'Magic': 1, 'Uncanny Being': 1 }, hooks: ['magie','natur'], examples: ['ein unsichtbarer Schattenwolf','eine Hexe mit Vertrautem','Geisterkind an seiner Seite'] },
    { title: 'Wissen über Dinge, die andere fürchten', text: 'Ich weiß, was im Schatten lauert. Sie wissen es nicht.', affinities: { 'Knowledge': 3, 'Uncanny Being': 1 }, hooks: ['wissen','geheimnis'], examples: ['ein verbannter Dämonenkundler','eine Jägerin der Unsichtbaren','Flüstern aus alten Gräbern'] },
    { title: 'Ich bin etwas anderes als ein Mensch', text: 'Mein Blut weiß es. Mein Spiegelbild auch.', affinities: { 'Uncanny Being': 3, 'Trait': 1, 'Monstrosity': 1 }, hooks: ['außenseiter','schicksal'], examples: ['ein halbblütiger Feenspross','eine getarnte Gestaltwandlerin','Spiegelbild zeigt Hörner'] },
    { title: 'Ich beherrsche etwas wie niemand sonst', text: 'Ich weiß nicht, woher es kommt. Es ist einfach immer da gewesen.', affinities: { 'Prodigious Ability': 3, 'Mastery': 2 }, hooks: ['handwerk','schicksal'], examples: ['ein begnadeter Schwertvirtuose','eine instinktive Bogenschützin','Hände formen perfekte Klingen'] },
    { title: 'Ich bin mächtiger als alle hier wissen', text: 'Ich zeige es ihnen nur, wenn mir keine Wahl bleibt.', affinities: { 'Monstrosity': 2, 'Dominion': 2, 'Destiny': 1 }, hooks: ['macht','geheimnis'], examples: ['ein verkleideter Drachenfürst','eine schlummernde Tyrannin','verborgene Krone unterm Lumpen'] },
    // Antrieb & Verwundbarkeit
    { title: 'Ich suche jemanden, den ich verloren habe', text: 'Sein/ihr Name ist mein erstes Wort beim Aufwachen.', affinities: { 'Devotion': 2, 'People': 1, 'Duty': 1 }, hooks: ['verlust','glaube'], examples: ['eine suchende Schwester','ein treuer Geliebter','Wallfahrt zum letzten Brief'] },
    { title: 'Ich will herausfinden, was ich wirklich bin', text: 'Es gibt eine Antwort. Ich hoffe, ich kann mit ihr leben.', affinities: { 'Past': 2, 'Uncanny Being': 1, 'Destiny': 2 }, hooks: ['schicksal','geheimnis'], examples: ['ein gedächtnisloser Wiedergänger','eine Tochter unbekannter Herkunft','Prophezeiung über sein Blut'] },
    { title: 'Ich vertraue niemandem mehr', text: 'Einmal war einmal zu oft.', affinities: { 'Personality': 2, 'Past': 1, 'Influence': 1 }, hooks: ['außenseiter','verlust'], examples: ['ein vernarbter Einzelgänger','eine verratene Spionin','ein misstrauischer Kopfgeldjäger'] },
    { title: 'Mein Stolz ist mein größtes Problem', text: 'Ich weiß es. Und tue trotzdem nichts dagegen.', affinities: { 'Personality': 2, 'Mastery': 1, 'Circumstance': 1 }, hooks: ['adel'], examples: ['ein hochmütiger Schwertmeister','eine entthronte Adlige','ein eitler Duellant'] },
    { title: 'Ich habe einen Schwur zu erfüllen', text: 'Worte, die ich nicht zurücknehmen kann. Ich will es auch nicht.', affinities: { 'Devotion': 2, 'Duty': 3 }, hooks: ['glaube'], examples: ['eine eidgebundene Ritterin','ein geweihter Tempelwächter','der letzte Schwurbruder'] },
    { title: 'Ich will gegen ein Unrecht kämpfen', text: 'Solange es steht, schlafe ich nicht ruhig.', affinities: { 'Duty': 2, 'Devotion': 2, 'Influence': 1 }, hooks: ['kampf','glaube'], examples: ['eine aufständische Rebellin','ein gefallener Inquisitor','Klinge gegen den Tyrannen'] },
    { title: 'Ich habe eine Schuld zu begleichen', text: 'Sie steht in mir wie ein Stein. Eines Tages werfe ich ihn.', affinities: { 'Past': 2, 'Duty': 1, 'People': 1 }, hooks: ['verlust','glaube'], examples: ['ein reuiger Gesetzloser','eine verschuldete Söldnerin','Blutschuld am Familiengrab'] },
    { title: 'Ich will bewahren, was mir wirklich wichtig ist', text: 'Nicht alles wird ersetzt. Manches ist unwiederbringlich.', affinities: { 'Possessions': 2, 'Companion': 2, 'People': 1 }, hooks: ['glaube','natur'], examples: ['eine wandernde Hüterin','ein treuer Wolfsgefährte','der letzte Hain-Wächter'] },
    { title: 'Ich will das Beste von mir zeigen', text: 'Einmal. Für die richtigen Menschen. Zur richtigen Zeit.', affinities: { 'Prodigious Ability': 2, 'Mastery': 2, 'Personality': 1 }, hooks: ['handwerk'], examples: ['eine ehrgeizige Meisterschmiedin','ein verkannter Wunderbarde','ein aufstrebender Turnierkämpfer'] },
    { title: 'Ich will das zurückerobern, was mir gehört', text: 'Das Recht ist klar. Nur die Welt ist blind dafür.', affinities: { 'Dominion': 2, 'Monstrosity': 1, 'Duty': 1 }, hooks: ['macht','adel'], examples: ['ein verbannter Thronerbe','eine enteignete Hexenkönigin','die entrissene Krone zurückerobern'] }
  ];
  // Einzelne Phase mit allen Karten
  PHASES.splice(0, PHASES.length, {
    id: 1, title: '', eyebrow: '',
    cards: newCards
  });
})();
