/* =====================================================
   phases_patch.js — Einzelner Kartenstapel (40 Karten)
   Keine Phasen mehr — ein gemischter Stapel.
   hooks: thematische Schlagworte (Swipe-Bias). Kanonisches Vokabular:
   adel, außenseiter, geheimnis, magie, wissen, handwerk, glaube, kampf,
   natur, stadt, verlust, macht, fahrend, schicksal
   text: umfangreiches Hintergrund-Puzzleteil (ergänzt den Titel, nennt ihn nicht).
   examples: kurze Helden-Archetypen (für die „etwa:"-Zeile auf der Swipe-Karte).
===================================================== */
(function() {
  var newCards = [
    // Welt & Atmosphäre
    { title: 'Ein Hof am Waldrand bei Nebel', text: 'Die Großmutter lehrte dich, den Wald zu lesen, doch eines Morgens war sie fort und nur die Tiere blieben. Seitdem hütest du ein Wissen, das nicht für Menschen gedacht war.', affinities: { 'Skill or Trade': 2, 'People': 2, 'Companion': 1 }, hooks: ['natur','geheimnis'], examples: ['Wildhüterin','Fährtenleser','Einsiedlerin'] },
    { title: 'Eine zerstörte Burg, in der noch jemand wohnt', text: 'In den Trümmern deines Geschlechts klammerst du dich an einen letzten Schatz und einen Titel, den niemand mehr anerkennt. Was du bewachst, könnte dein Untergang sein.', affinities: { 'Circumstance': 2, 'Relic': 1, 'Dominion': 2 }, hooks: ['geheimnis','verlust','macht'], examples: ['Erbin','Burgvogt','Verbannter'] },
    { title: 'Marktplatz, Geschrei, Diebesfinger', text: 'Im Gedränge lerntest du, dass flinke Finger mehr wert sind als ein ehrlicher Name. Doch der falsche Beutel brachte dir mächtige Feinde ein.', affinities: { 'Skill or Trade': 2, 'Personality': 2, 'Influence': 1 }, hooks: ['stadt'], examples: ['Diebin','Gaukler','Hehler'] },
    { title: 'Ein Buch, das niemand lesen sollte', text: 'Du fandest die Seiten in einem verschlossenen Schrein und brachst das Siegel trotz aller Warnungen. Nun flüstert das Geschriebene in deinen Träumen weiter.', affinities: { 'Knowledge': 3, 'Magic': 1, 'Relic': 1 }, hooks: ['wissen','geheimnis','magie'], examples: ['Gelehrter','Beschwörerin','Ketzer'] },
    { title: 'Ein Schwur am Sterbebett', text: 'Mit kalter Hand in deiner versprachst du etwas, das dein Leben für immer band. Jeden Tag fragst du dich, ob die Toten zusehen.', affinities: { 'Devotion': 3, 'Duty': 2 }, hooks: ['glaube','verlust'], examples: ['Ritterin','Pilger','Rächer'] },
    { title: 'Eine alte Schmiede mit Funkenflug', text: 'Am Amboss deines Meisters lerntest du, Metall zu zähmen, bis deine Klingen einen Namen bekamen. Doch eine Waffe, die du schmiedetest, fiel in die falschen Hände.', affinities: { 'Skill or Trade': 3, 'Mastery': 1, 'Possessions': 1 }, hooks: ['handwerk'], examples: ['Schmiedin','Waffenmeister','Handwerker'] },
    { title: 'Ein Saal voll mit Adligen', text: 'Zwischen Seide und Lächeln lerntest du, dass jedes Wort eine Klinge ist. Ein Geheimnis, das du am Hof aufschnapptest, macht dich nun gefährlich.', affinities: { 'Circumstance': 2, 'Influence': 2, 'Dominion': 1 }, hooks: ['adel','macht'], examples: ['Höfling','Intrigantin','Diplomat'] },
    { title: 'Ein Kreis aus Kerzen, mitten in der Nacht', text: 'Im Kerzenschein riefst du etwas an, das nicht antworten sollte, und etwas antwortete doch. Seither brennt in dir ein Licht, das du nicht mehr löschen kannst.', affinities: { 'Magic': 3, 'Knowledge': 1, 'Devotion': 1 }, hooks: ['magie','geheimnis'], examples: ['Hexe','Medium','Eingeweihter'] },
    { title: 'Das Rumpeln tief unter der alten Erde', text: 'Etwas Uraltes regt sich im Gestein und ruft nach dir allein. Niemand sonst hört es, doch du weißt, dass es deinen Namen kennt.', affinities: { 'Monstrosity': 3, 'Destiny': 2 }, hooks: ['schicksal','geheimnis'], examples: ['Auserwählte','Bergwanderer','Wächter'] },
    { title: 'Eine Meisterin, die keine Worte braucht', text: 'Deine Hände sprechen, wo Sprache versagt, und das Werkzeug gehorcht wie ein zweiter Atem. Doch Lehrlinge fürchten dein Schweigen mehr als jeden Tadel.', affinities: { 'Mastery': 3, 'Prodigious Ability': 2 }, hooks: ['handwerk'], examples: ['Meisterin','Stumme','Schmiedin'] },
    // Herkunft & Hintergrund
    { title: 'Aus einer alten Familie mit Geheimnissen', text: 'Hinter den Porträts der Ahnen verbergen sich Pakte, von denen niemand mehr sprechen darf. Eines Tages wird man auch von dir Schweigen verlangen.', affinities: { 'People': 2, 'Past': 1, 'Dominion': 1, 'Circumstance': 1 }, hooks: ['adel','geheimnis'], examples: ['Erbin','Geheimnisträger','Spross'] },
    { title: 'Aufgewachsen unter Fremden', text: 'Niemand teilte dein Blut, doch viele teilten ihr Brot mit dir. Du lerntest jede Sprache der Straße, bliebst aber in jeder ein Gast.', affinities: { 'Past': 1, 'Circumstance': 2, 'Personality': 1, 'Influence': 1 }, hooks: ['außenseiter','verlust'], examples: ['Findelkind','Vagabund','Übersetzerin'] },
    { title: 'Im Krieg verloren, im Frieden nicht heimisch', text: 'Die Schlachten endeten, doch in deinem Schlaf marschieren sie weiter. Daheim trägt man Gesichter, die du nicht mehr zu deuten weißt.', affinities: { 'Past': 1, 'Duty': 2, 'Influence': 1 }, hooks: ['kampf','verlust'], examples: ['Veteran','Söldnerin','Heimkehrer'] },
    { title: 'Der einzige Überlebende meines Dorfes', text: 'Die Asche deines Dorfes klebt dir noch an den Sohlen, als du dem Gott dafür dankst, dass du lebst. Warum gerade du verschont bliebst, lässt dich nachts nicht ruhen.', affinities: { 'Past': 1, 'People': 2, 'Devotion': 1, 'Destiny': 1 }, hooks: ['verlust','glaube'], examples: ['Pilgerin','Zeuge','Geweihte'] },
    { title: 'Meine Familie übte ein Handwerk seit Generationen', text: 'Vom Großvater erbtest du die Werkzeuge, vom Vater den Stolz und die Schulden. Der Name über der Werkstatt ist eine Last, die du nicht abzulegen wagst.', affinities: { 'Skill or Trade': 3, 'People': 1, 'Possessions': 1 }, hooks: ['handwerk'], examples: ['Handwerker','Erbin','Zunftmeister'] },
    { title: 'Adelige Erziehung, eigene Wege', text: 'Man lehrte dich Etikette und Tanz, doch dein Herz schlug stets für die Gassen jenseits der Mauern. Den Namen deines Hauses trägst du wie ein zu enges Gewand.', affinities: { 'Circumstance': 2, 'Personality': 2, 'Influence': 1 }, hooks: ['adel','außenseiter'], examples: ['Abtrünnige','Edelmann','Wanderin'] },
    { title: 'Aufgewachsen mit ungewöhnlichen Lehrern', text: 'Eine blinde Seherin lehrte dich Sterndeutung, ein Rabe das Schweigen. Was sie dir wirklich beibringen wollten, begreifst du erst jetzt.', affinities: { 'Knowledge': 2, 'Magic': 2, 'Trait': 1 }, hooks: ['wissen','magie'], examples: ['Gelehrter','Zauberschülerin','Adept'] },
    { title: 'Ich war nie wie die anderen', text: 'Schon als Kind wichen dir die Schatten aus und die Hunde knurrten. Niemand sprach es aus, doch alle wussten, dass etwas in dir fremd war.', affinities: { 'Trait': 3, 'Personality': 1, 'Uncanny Being': 1 }, hooks: ['außenseiter','schicksal'], examples: ['Wechselbalg','Außenseiterin','Gezeichneter'] },
    { title: 'Ich war für etwas Großes vorgesehen', text: 'Eine Prophezeiung nannte deinen Namen, bevor du laufen konntest. Doch niemand verriet dir, ob das Große ein Segen oder ein Joch sein würde.', affinities: { 'Destiny': 3, 'Dominion': 1 }, hooks: ['schicksal','macht'], examples: ['Erbin','Auserwählter','Thronfolgerin'] },
    { title: 'Ich habe etwas Wichtiges geerbt, das mich verfolgt', text: 'Das versiegelte Kästchen deiner Großmutter flüstert nachts deinen Namen. Wer es haben will, schreckt vor keinem Mittel zurück.', affinities: { 'Relic': 3, 'Possessions': 2 }, hooks: ['geheimnis','schicksal'], examples: ['Erbe','Hüterin','Gejagter'] },
    // Können & Wesen
    { title: 'Ein altes Schwert, das nur ich führen kann', text: 'Andere zerbrachen sich die Hände an seinem Griff, doch dir gehorcht die Klinge wie ein altes Versprechen. Sie verlangt einen Preis, den du noch nicht kennst.', affinities: { 'Relic': 2, 'Possessions': 1, 'Mastery': 1 }, hooks: ['kampf','schicksal'], examples: ['Klingenträger','Auserwählte','Schwertmeister'] },
    { title: 'Ich verstehe, was Tiere sagen', text: 'Eine Eule warnte dich vor dem Feuer, ein Fuchs verriet dir den Verräter. Doch seit jenem Tag schweigen die Menschen lauter als jedes Tier.', affinities: { 'Magic': 2, 'Companion': 2, 'Trait': 1 }, hooks: ['natur','magie'], examples: ['Tiersprecherin','Druide','Wildläufer'] },
    { title: 'Ich kann Wunden flicken, die andere nicht können', text: 'Wo Wundärzte aufgaben, schlossen sich unter deinen Fingern die Risse. Manche nennen es Gnade, andere bekreuzigen sich hinter deinem Rücken.', affinities: { 'Skill or Trade': 2, 'Knowledge': 2, 'Devotion': 1 }, hooks: ['handwerk','glaube'], examples: ['Heilerin','Wundärztin','Geweihter'] },
    { title: 'Ich bin schneller, als jemand wie ich sein dürfte', text: 'Du warst beim Becher, bevor die Klinge fiel, am Tor, ehe es schloss. Etwas in deinem Blut zählt schneller als die Welt um dich her.', affinities: { 'Trait': 3, 'Prodigious Ability': 2 }, hooks: ['schicksal'], examples: ['Läufer','Wunderkind','Klingentänzerin'] },
    { title: 'Eine Magie, die ich nicht ganz beherrsche', text: 'Manchmal antwortet die Kraft auf Worte, die du nie gelernt hast. Du fürchtest den Tag, an dem sie sich gegen dich richtet.', affinities: { 'Magic': 3, 'Uncanny Being': 1 }, hooks: ['magie'], examples: ['Beschwörerin','Hexenkind','Wandlerin'] },
    { title: 'Ein Wesen, das mir folgt und mir gehört', text: 'Es kam in einer Nacht zu dir und ging nie wieder fort. Niemand weiß, ob du es führst oder es dich.', affinities: { 'Companion': 3, 'Magic': 1, 'Uncanny Being': 1 }, hooks: ['magie','natur'], examples: ['Vertrauter','Bändigerin','Gefährte'] },
    { title: 'Wissen über Dinge, die andere fürchten', text: 'In vergilbten Seiten fandest du Namen, die man nicht laut spricht. Seither weichen dir manche Blicke aus.', affinities: { 'Knowledge': 3, 'Uncanny Being': 1 }, hooks: ['wissen','geheimnis'], examples: ['Gelehrte','Ketzer','Geheimniswahrer'] },
    { title: 'Ich bin etwas anderes als ein Mensch', text: 'Unter deiner Haut regt sich etwas, das nie ganz schlief. Die Dörfer, durch die du ziehst, spüren es vor dir.', affinities: { 'Uncanny Being': 3, 'Trait': 1, 'Monstrosity': 1 }, hooks: ['außenseiter','schicksal'], examples: ['Außenseiterin','Wechselbalg','Gezeichneter'] },
    { title: 'Ich beherrsche etwas wie niemand sonst', text: 'Was anderen Jahre kostet, gelang dir beim ersten Versuch. Doch jede Meisterschaft fordert einen Preis, den du noch zahlst.', affinities: { 'Prodigious Ability': 3, 'Mastery': 2 }, hooks: ['handwerk','schicksal'], examples: ['Virtuose','Meisterin','Wunderkind'] },
    { title: 'Ich bin mächtiger als alle hier wissen', text: 'Sie sehen einen Reisenden, einen Diener, eine Niemand. Was unter dieser Maske schläft, würde sie auf die Knie zwingen.', affinities: { 'Monstrosity': 2, 'Dominion': 2, 'Destiny': 1 }, hooks: ['macht','geheimnis'], examples: ['Erbin','Tyrann','Verborgene'] },
    // Antrieb & Verwundbarkeit
    { title: 'Ich suche jemanden, den ich verloren habe', text: 'An jeder Kreuzung fragst du nach einem Gesicht, das nur du noch kennst. Der Glaube, dass es noch atmet, hält dich auf den Beinen.', affinities: { 'Devotion': 2, 'People': 1, 'Duty': 1 }, hooks: ['verlust','glaube'], examples: ['Suchende','Pilger','Treuer'] },
    { title: 'Ich will herausfinden, was ich wirklich bin', text: 'In deiner Erinnerung klafft ein Loch, wo dein Anfang sein sollte. Jede Spur, der du folgst, flüstert eine andere Antwort.', affinities: { 'Past': 2, 'Uncanny Being': 1, 'Destiny': 2 }, hooks: ['schicksal','geheimnis'], examples: ['Heimatlose','Findelkind','Wanderer'] },
    { title: 'Ich vertraue niemandem mehr', text: 'Ein Verrat hat dich gelehrt, dass jedes Lächeln eine Maske sein kann. Seitdem prüfst du jeden Blick und schläfst nie mit dem Rücken zur Tür.', affinities: { 'Personality': 2, 'Past': 1, 'Influence': 1 }, hooks: ['außenseiter','verlust'], examples: ['Einzelgänger','Spion','Deserteur'] },
    { title: 'Mein Stolz ist mein größtes Problem', text: 'Lieber gingst du allein zugrunde, als um Hilfe zu bitten. Dein Name öffnet Türen, doch deine Sturheit hat schon zu viele wieder zugeschlagen.', affinities: { 'Personality': 2, 'Mastery': 1, 'Circumstance': 1 }, hooks: ['adel'], examples: ['Adliger','Duellant','Erbin'] },
    { title: 'Ich habe einen Schwur zu erfüllen', text: 'An einem Sterbebett oder vor einem Altar hast du ein Versprechen gegeben, das dich seither treibt. Bricht es dich, wenn du es hältst oder erst, wenn nicht?', affinities: { 'Devotion': 2, 'Duty': 3 }, hooks: ['glaube'], examples: ['Paladin','Pilgerin','Ordensbruder'] },
    { title: 'Ich will gegen ein Unrecht kämpfen', text: 'Du hast einmal weggesehen, als andere litten, und die Scham frisst noch immer. Nun erhebst du das Schwert für jene, die keine Stimme haben.', affinities: { 'Duty': 2, 'Devotion': 2, 'Influence': 1 }, hooks: ['kampf','glaube'], examples: ['Rebellin','Kreuzritter','Richterin'] },
    { title: 'Ich habe eine Schuld zu begleichen', text: 'Jemand starb, damit du leben konntest, und diese Rechnung ist nie beglichen. Du suchst die Hinterbliebenen auf, ehe dich die Reue ganz verzehrt.', affinities: { 'Past': 2, 'Duty': 1, 'People': 1 }, hooks: ['verlust','glaube'], examples: ['Büßer','Eidvollstrecker','Waise'] },
    { title: 'Ich will bewahren, was mir wirklich wichtig ist', text: 'Einmal hast du alles verloren, weil du es nicht festhieltst. Jetzt legst du dich mit Sturm und Mensch an, um den letzten Funken Heimat zu schützen.', affinities: { 'Possessions': 2, 'Companion': 2, 'People': 1 }, hooks: ['glaube','natur'], examples: ['Hüterin','Hirte','Wächter'] },
    { title: 'Ich will das Beste von mir zeigen', text: 'Ein Meister verspottete dein Talent, und seither willst du es allen beweisen. Jedes Werk deiner Hände soll lauter sprechen als jeder Zweifel.', affinities: { 'Prodigious Ability': 2, 'Mastery': 2, 'Personality': 1 }, hooks: ['handwerk'], examples: ['Handwerkerin','Virtuose','Lehrling'] },
    { title: 'Ich will das zurückerobern, was mir gehört', text: 'Man riss dir Titel und Land aus den Fingern, vielleicht durch eine Bestie, vielleicht durch Verrat. Du kehrst zurück, bereit, dein Erbe in Blut neu zu schreiben.', affinities: { 'Dominion': 2, 'Monstrosity': 1, 'Duty': 1 }, hooks: ['macht','adel'], examples: ['Thronerbin','Eroberer','Verstoßene'] }
  ];
  // Einzelne Phase mit allen Karten
  PHASES.splice(0, PHASES.length, {
    id: 1, title: '', eyebrow: '',
    cards: newCards
  });
})();
